### ISSUE TITLE
 refer to db field value when query or update

### ISSUE THREAD

**Issue by Ackerr** [ent/ent#1278]
I want to execute sql like this 

```
select a,b from demo where a = b + 1
or
update demo set a = a + 1
```
I took a quick look at the documentation，but not find how to implement it.

**Comment by a8m** [comment]
Hey @Ackerr, 
You can use the `Add<F>()` setters, in order to increment/decrement number fields. For example:

```go
client.T.Update().AddPrice(1).Exec(ctx)
```

And for the first example, you can use the `Select` option to select specific fields, and custom predicates for writing such filters. For example:

```go
client..User.Query().
	Where(func(s *sql.Selector) {
		s.Where(sql.ExprP("a = b + ?", 1)) // or, use sql.P with custom builder.
	}).
	Select(user.FieldA, user.FieldB).
	All(ctx)
```

Closing, but please feel free to reopen if you have more questions. Thanks 🙏

**Comment by Ackerr** [comment]
Thanks. Now i need to implement a feature, sql like 
```
update demo set code=CONCAT('9',  LPAD(type, 2, 0), LPAD(id, 12, 0)) where key='key'
```

1. Does ent can use mysql buildin func like CONCAT，LAPD? 
2. Is there any way to directly execute raw sql like sql.DB().Exec('sql')
