### ISSUE TITLE
Add interface for field builder to make partial prebuild field

### ISSUE THREAD

**Issue by wenerme** [ent/ent#1381]
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

```go
func IDField(name string)  StringFieldBuilder  {
	return field.String(name).GoType(models.ID(""))
}
```

Current return `*stringBuilder`, can not make this happen.

## Motivation 🔦
* Customize ID field are spread everywhere in schema, every id field need to repeat this
* Make Customized field build easier, like a helper to inject customized default handling

**Comment by giautm** [comment]
Hi, you can use [Schema Mixin](https://entgo.io/docs/schema-mixin) to share common fields with all entities.

**Comment by wenerme** [comment]
@giautm I fixed the demo code, what I want is make

```go
func (Ent)Fields(name string) []ent.Field {
	return []ent.Field {
		field.String("productID").GoType(models.ID("")),
		field.String("orderID").GoType(models.ID("")),
		field.String("accountID").GoType(models.ID("")),
		field.String("contactID").GoType(models.ID("")),
	}
}
```

become

```go
func (Ent)Fields(name string) []ent.Field {
	return []ent.Field {
		IDField("productID"),
		IDField("orderID"),
		IDField("accountID"),
		IDField("contactID"),
	}
}
```

**Comment by a8m** [comment]
You can return an `ent.Field` from your helper function.

```go
func IDField(name string) ent.Field  {
	return field.String(name).GoType(models.ID(""))
}
```

But if you want to have something like `IDField("foo").Optional()`, it won't work. 

If your use-case requires changing all fields (e.g. adding an annotation to all fields), you can do it using the `Descriptor` method, as [in this example](https://github.com/ent/ent/blob/master/schema/mixin/mixin.go#L105-L112).

**Comment by wenerme** [comment]
@a8m make `IDField("foo").Optional()` work that's why I propose the change.

Maybe I should use the Descriptor, write a build from scratch.

**Comment by nix-sys** [comment]
Hi there,
@a8m Following up on the field template idea: Is there a reason why the fieldBuilders (stringBuilder, etc.) are kept as unexported variables? 

For our own use case it would save us a ton of time if the fieldBuilders were accessible by our own packages:
- we use nanoids with custom prefix
- have company wide policies like *no empty strings* `""` in the db (either `null` or `"some string"`)
- various custom go / sql types for business specific reasons. 

Our field definitions look like this:
```go
func PrimaryNanoID(fieldname string, prefix prefixes.Prefix) ent.Field {
	fieldname = strings.ToLower("id")

	return field.String("id").
		StorageKey(fieldname).
		GoType(nanoid.NanoID("")).
		DefaultFunc(prefix.NewNanoID).
		Match(regexp.MustCompile("^" + string(prefix) + "_[A-Za-z0-9]{19,25}$")).
		NotEmpty().
		Immutable().
               Annotations(
		entsql.Checks(map[string]string{
			fmt.Sprintf(`%v_valid_key`, fieldname):        fmt.Sprintf(`(%v ~ '^%v_[A-Za-z0-9]*$')`, fieldname, string(prefix)),
			fmt.Sprintf(`%v_non_empty_string`, fieldname): fmt.Sprintf(`(utils.null_or_non_empty_trimmed_string(%v))`, fieldname),
		}),
	)
}

func PrimaryNanoID(fieldname string, prefix prefixes.Prefix) ent.Field {
	fieldname = strings.ToLower("id")

	return field.String("id").
		StorageKey(fieldname).
		GoType(nanoid.NanoID("")).
		DefaultFunc(prefix.NewNanoID).
		Match(regexp.MustCompile("^" + string(prefix) + "_[A-Za-z0-9]{19,25}$")).
		NotEmpty().
		Immutable().
               Annotations(
		entsql.Checks(map[string]string{
			fmt.Sprintf(`%v_valid_key`, fieldname):        fmt.Sprintf(`(%v ~ '^%v_[A-Za-z0-9]*$')`, fieldname, string(prefix)),
			fmt.Sprintf(`%v_non_empty_string`, fieldname): fmt.Sprintf(`(utils.null_or_non_empty_trimmed_string(%v))`, fieldname),
		}),
	)
}
```

Having to define fields like that on 20+ tables is quite painful & error prone.
- mixin won't work, since the fields have individual properties (field name, prefix, optional)
- a func with an `ent.field` return doesn't really work either, since then functionalities like the `field.Annotation(entsql.Checks:...)` don't seem to work anymore (we've spent quite some time experimenting with that)

### Solution
The solutions seems to be quite simple:
If the unexported typeBuilders in `entgo.io/schema/field.go` would be changed to exported (`type stringBuilder struct {}` -> `type StringBuilder struct {}`), we could use them as our func returns and we could easily define our policies once and then use them in a very clean way:
```go
customfield.PrimaryNanoID(prefixes.FileID)
customfield.String("ref_id", "this is a reference to xy")
//and even 
customfield.String("ref_id", "this is a reference to xy").Optional()
```


### Advantages
   - custom primary keys like pulid, nanoid etc. with custom prefixes `usr_` per table with an automatic regex validation based on the used prefix
   - set a constraint on all string fields to prevent empty strings `""` (either `null` or `some string`)
   - assigning all `field.Time` datatypes to a specific mysql/postgres datatype
   - at the same time keeping the flexibility to make a field optional by choice 
   - enforce company wide policies, avoid errors and promote more consistency in the code base / db
=> we would consider to define templates almost all of our field types.

@a8m If nothing speaks against it, I'm happy to create a pull request for that...
