### ISSUE TITLE
Question: How to use subquery in query

### ISSUE THREAD

**Issue by chrisguox** [ent/ent#1393]
Hello, teams :)
thank you for working hard for the awesome project.

I want to implement some logic like this, which  like I saw in #92.

```
SELECT DISTINCT `todos`.`id`, `todos`.`text`, `todos`.`done` 
    FROM `todos` WHERE `todos`.`user_id` IN (
        SELECT `id` FROM `users` WHERE `users`.`id` IN (?, ?)
    )
```

but I didn't create any relation(edge) for 2 tables.
I don't know how to add a custom subquery in query, and I can't find any case in docs or past issues.

then I've come to ask for your help. Thx again.

**Comment by a8m** [comment]
Hey @chrisguox and thanks for raising up this question. 

You can pass a [custom predicate](https://entgo.io/docs/predicates/#custom-predicates) to the `Where` method as follow:

```go
client.Todo.Query().
    Where(func(s *sql.Selector) {
        t := sql.Table(user.Table)
        s.Where(
            sql.In(
                s.C(todo.FieldUserID),
                sql.Select(t.C(user.FieldID)).From(t).Where(sql.In(t.C(user.FieldID), ids...)),
            ),
        )
    })
```
The example above is a bit verbose, but it's because we use the generated constants (you can also pass raw strings, which is less recommended).

BTW, if you're filtering only by the "user_id"/"id" field, you don't need this sub-query. Instead, use:

```go
client.Todo.Query().Where(todo.UserIDIn(ids...))
```

Please close this issue if it does answer your question, and feel free to add this example to [custom predicates](https://github.com/ent/ent/blob/master/doc/md/predicates.md#custom-predicates) section in our docs. Thanks 🙏

**Comment by chrisguox** [comment]
> The example above is a bit verbose, but it's because we use the generated constants (you can also pass raw strings, which is less recommended).

yeah, it's necessary for ORM in some case.
the problem is about code-first or database-first, then I will follow this way to write : )


> Please close this issue if it does answer your question, and feel free to add this example to custom predicates section in our docs. Thanks 🙏

yeah, it does, and thank you sooooooo much to save my time : )
I will create a pr about to update it.

**Comment by a8m** [comment]
Thanks @chrisguox 😃
