### ISSUE TITLE
Custom edges names

### ISSUE THREAD

**Issue by FournyP** [ent/ent#1396]
## Summary 💡

Hello everyone, I'm new in Golang and I have started to use Ent framework.

Firstly, I have an existing database generated thanks Doctrine 2 for a web app and I want to code a service with Golang to implement this database.

So I have a specific field name in my database for a relation :  "table_1_id".
But Ent framework generate a name like this : "table_1_table_2"

I have search in the documentation and in git issue but I never found what I want to do.

Someone know how can I do that ?

Thank you in advance and have a good day.

**Comment by a8m** [comment]
Hey @FournyP, I think the [edge.StorageKey](https://entgo.io/docs/schema-edges/#storagekey) should solve your problem here, right? 

Please let me know if it does solve your problem and I can close this issue. Also, feel free to join our [Slack channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53).

**Comment by FournyP** [comment]
Hey @a8m,

Exactly, edge.StorageKey solve the problem, thanks a lot for your answer

Have a good day
