### ISSUE TITLE
field.Proto for storing protobuf in database

### ISSUE THREAD

**Issue by pontaoski** [ent/ent#1422]
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

It should work essentially equivalently to `field.Json`, but instead of marshalling and unmarshalling from JSON, it does so for protobuf.

## Motivation 🔦

We have some protobuf structs that we can already use field.JSON for, but some of them don't work with the stdlib json marshalling and unmarshalling, so they need to be marshalled and unmarshalled using the protobuf library's methods.

**Comment by rotemtam** [comment]
Hi @pontaoski,
Thanks for reaching out!

Here's an approach that I hope will solve your requirement: 

1. Assuming proto message:
```protobuf
message Hi {
  string Greeting = 1;
}
```
2. Have the pb struct implement `ValueScanner` ([doc](https://pkg.go.dev/entgo.io/ent/schema/field#ValueScanner)):
```go
func (x *Hi) Value() (driver.Value, error) {
	return proto.Marshal(x)
}

func (x *Hi) Scan(src interface{}) error {
	if src == nil {
		return nil
	}
	if b, ok := src.([]byte); ok {
		if err := proto.Unmarshal(b, x); err != nil {
			return err
		}
		return nil
	}
	return fmt.Errorf("unexpected type %T", src)
}
```
3.  Add the field to your schema as a `field.JSON`:
```go
// Message holds the schema definition for the Message entity.
type Message struct {
	ent.Schema
}

// Fields of the Message.
func (Message) Fields() []ent.Field {
	return []ent.Field{
		field.JSON("hi", &pb.Hi{}),
	}
}
```
3. Test it:
```go
package main

import (
	"context"
	"issue/ent/enttest"
	"issue/pb"
	"testing"

	_ "github.com/mattn/go-sqlite3"
	"github.com/stretchr/testify/require"
)

func Test(t *testing.T) {
	client := enttest.Open(t, "sqlite3", "file:ent?mode=memory&cache=shared&_fk=1")
	defer client.Close()

	msg := client.Message.Create().
		SetHi(&pb.Hi{
			Greeting: "hello",
		}).
		SaveX(context.TODO())

	ret := client.Message.GetX(context.TODO(), msg.ID)
	require.Equal(t, "hello", ret.Hi.Greeting)
}
```

### Caveats
Using `field.JSON` here is a bit awkward, since this isn't a JSON type in any way. It should have "just worked" with either `field.Bytes` or `field.Other` but there seems to be currently an issue with how the codegen currently treats structs as the backing GoType for this use-case (it works great with uuid.UUID for example). 

I've discussed this with @a8m and we will open a separate issue for this.

**Comment by a8m** [comment]
@rotemtam, the `GoType` issue was fixed. Can you give it another try?

**Comment by rotemtam** [comment]
@a8m , yes I can confirm pulling from ent@master this will also work:

```go
// Fields of the Message.
func (Message) Fields() []ent.Field {
	return []ent.Field{
		field.Bytes("hi").GoType(&pb.Hi{}),
	}
}
```

I will add something in this spirit to the documentation
