### ISSUE TITLE
Unmarshal database null to custom GoType nil not working

### ISSUE THREAD

**Issue by pzeinlinger** [ent/ent#1449]
- [x ] The issue is present in the latest commit on master.
- [x ] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Null values from the database are unmarshaled to zero values, when custom GoTypes are used for string field

## Expected Behavior 🤔

Null values should be represented by nil values

## Steps to Reproduce 🕹

Quick demo: https://github.com/pzeinlinger/ent-nil-demo

## Your Environment 🌎

entgo.io/ent v0.7.1-0.20210411114748-f59e25d22865
github.com/mattn/go-sqlite3 v1.14.6

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.2  |
| Ent         | 0.7.1-0.20210411114748-f59e25d22865   |
| Database    | sqlite3   |
| Driver      | https://github.com/mattn/go-sqlite3        |

**Comment by a8m** [comment]
Hey @pzeinlinger, I just checked this, and the `Nillable` option doesn't work also in v0.7.0 for custom Go types (before #1428 was added).

The reason for it is because the runtime code is not able to figure out if the scanned value is valid or not (unlike in all `database/sql` types that have a boolean field named `Valid`).

My suggestion is to add support for `Valid` method/field in the codegen and set the struct-field only if the custom-type is valid after calling to scan. The `Valid` field/method will indicate if the field is NULL or not in the database. The usage (in ent-codegen) will be as follows:

```go
if value, ok := values[i].(*domain.ExternalReference); !ok {
	return fmt.Errorf("unexpected type %T for field external_reference", values[i])
} else if value != nil && value.Valid { // value.Valid()
	n.ExternalReference = value
}
```
WDYT?

**Comment by a8m** [comment]
The other approach is to wrap the Go type with a custom scanner, that will tag the value as valid if it's not NULL.  

```go
type NullScanner struct {
	V sql.Scanner
	Valid bool
}
```

**Comment by mgabeler-lee-6rs** [comment]
I ran into this same issue today, updating my code to 0.8.0. I think the `NullScanner` pattern is much more intuitive for users. As a user, I'd expect my custom types to behave more or less the same as built-in types. If a `*string` or `*bool` can handle NULLs in the "natural" way, I'd intuitively expect a `*MyType` to do the same. Making that work also can avoid a bunch of excess code along the lines of `if entity.Field != nil && entity.Field.Valid ...`, and just bring it down to the `nil` check.

**Comment by a8m** [comment]
Yeah, I decided to go with the `NullScanner` option and I plan to send a patch for this soon.

**Comment by a8m** [comment]
Hey @pzeinlinger, the issue was fixed with https://github.com/ent/ent/pull/1469. The code now wraps nillable scanner types with `sql.NullScanner`, and assigns the value to the struct field only if the input is valid (not nil). But note that your custom type should handle null inputs as well.  The change is as follows:

```diff
 func (r *ExternalReference) Scan(value interface{}) error {
+       if value == nil {
+               return nil
+       }
        s, ok := value.(string)
```

I checked it on your repository btw and it worked. Closing 😃
