### ISSUE TITLE
Partial indexes support

### ISSUE THREAD

**Issue by sywesk** [ent/ent#1472]
- [x] I have searched the [issues](https://github.com/facebook/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Basic support for partial indexes (ie indexes over table subsets). 

## Motivation 🔦

Partial indexes are really helpful for unique indexes when combined with soft delete. To date, postgres & sqlite support this feature. Quick example:

```sql
CREATE UNIQUE INDEX test_idx ON some_table (some_field) WHERE deleted_at is null;
```

I would like to contribute this support to the entgo project. If you think this is a good idea, would it be possible to quickly describe how you envision this feature from a technical standpoint ? I'm not familiar with the internals of this project.

**Comment by cliedeman** [comment]
I investigated this a while back so I can write down some pointers. I suggest you start with either postgres or sqlite to keep the pr smaller for the first pass

Steps:

1. Add `WhereClause` field to `schema.Index` struct
2. Add `WhereClause` to the `entsql.Annotation` so that users can specify a partial index
3. Amend the indexes method in schema for the postgres dialect to populate the `WhereClause`
4. Amend the schema unit tests to test this field is correctly populated
5. Change schema/changeset to account for `WhereClause` changes in indices
6. Modify schema/postgres.go `addIndex` to include the `WhereClause` when creating indices
7. Changed the schema.tmpl to generate the `WhereClause` from the `entsql.Annotation`
8. Add an integration tests

While this is everything that needs to be done I suggest you start with the smallest PR possible. Maybe just 1, 3 and 4

### Updated Postgres Query

```sql
SELECT i.relname AS index_name,
       a.attname AS column_name,
       idx.indisprimary AS primary,
       idx.indisunique AS unique,
       array_position(idx.indkey, a.attnum) as seq_in_index,
       pg_get_expr(idx.indpred, idx.indrelid) as where_clause # <- Added where clause
FROM pg_class t,
     pg_class i,
     pg_index idx,
     pg_attribute a,
     pg_namespace n
WHERE t.oid = idx.indrelid
  AND i.oid = idx.indexrelid
  AND n.oid = t.relnamespace
  AND a.attrelid = t.oid
  AND a.attnum = ANY(idx.indkey)
  AND t.relkind = 'r'
  AND n.nspname = %s
  AND t.relname = '%s'
ORDER BY index_name, seq_in_index;
```

### Expected Issues

The `pg_index.indpred` column is a compiled field. This makes checking for changed indexes difficult because the sql may not match

Given the following ddl

```sql
CREATE TABLE users
(
    id       BIGINT primary key,
    username varchar,
    active   bool
);
CREATE INDEX idx1 ON users (username);
CREATE INDEX idx2 ON users (username) where active = true;
CREATE INDEX idx3 ON users (username) where (active = true);
CREATE INDEX idx4 ON users (username) where (ACTIVE = true);
CREATE INDEX idx5 ON users (username) WhErE (active = TRUE);
```

Retrieving the where_clause will always return `(active = true)`. So Even if you remove the brackets if there is a slight different in the `ent.Annotation` definition the index will be re-created each time

### SQLite

The only way I could find to retrieve the where clause in sqlite is with the query

```sql
select * from sqlite_master where type = 'index';
```

We will have to manually parse the output though 😕

| type | name | tbl\_name | rootpage | sql |
| :--- | :--- | :--- | :--- | :--- |
| index | idx1 | users | 37 | CREATE INDEX idx1 ON users\(username\) WHERE active IS true |
| index | idx2 | users | 2 | CREATE INDEX idx2 ON users \(username\) WHERE active = true |
| index | idx3 | users | 3 | CREATE INDEX idx3 ON users \(username\) WHERE ACTIVE IS true |
| index | idx4 | users | 4 | CREATE INDEX idx4 ON users \(username\) whEre ACTIVE is true |

**Comment by sywesk** [comment]
Thanks @cliedeman for your precious inputs. I'm starting working on it.

**Comment by sywesk** [comment]
Hello @a8m ! I might have some questions to ask. I started working on it some days ago, but then got a bit overwhelmed by my work :sweat_smile: I'll open the PR soon to have a working base

**Comment by xu568** [comment]
Do we have any updates on this? I think it is a very useful feature.

**Comment by ivanvanderbyl** [comment]
It looks like this feature has been abandoned. @a8m any pointers on how this could be achieved with Atlas hooks?

**Comment by a8m** [comment]
Thanks for the reminder @ivanvanderbyl. This feature was actually implemented by Atlas a long time ago and the binding between the two packages was a small annotation change. It is resolved now by https://github.com/ent/ent/pull/2944 and the website will be updated soon.
