### ISSUE TITLE
Extend External Template Support

### ISSUE THREAD

**Issue by masseelch** [ent/ent#1655]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

1. Currently every templates one adds to extend ent is run against the `Graph`. I'd like to be able to run templates against the `Type`s. 
2. Another feature I'd like to see is to be able to define templates that do not result in another file generated.

## Motivation 🔦
I am trying to extend `ent` in the way its done by `entql`. I am implementing crud http handlers. There are two issues, that came up while doing so:

1. If one creates a lot of code per `Type` the generated file gets huge, since there is one created for the whole `Graph`.
2. If I am to define helper templates, `ent` tries to generate a go file out of them.

```go
{{ define "http/create" }}
  {{- with extend $ "Package" "http" -}}
    {{ template "header" . }}
  {{ end }}

  {{ range $node := $.Nodes }}
    // This is {{ $node.Name }} create handler
    {{ template "helper" }}
  {{ end }}
{{ end }}

{{ define "helper" }}
  // some stuff
{{ end }}
```
The template above will create one file `http/create.go`, that has every single `Type` in it. I'd like to be able to have several files `http/type1_create.go`, `http/type1_read.go`, `http/type2_create.go`, ...
Having defined the template `helper` results in ent creating a file `helper.go` with `// some stuff` as content, which is not a valid go file.

**Comment by masseelch** [comment]
@a8m I was able to do bullet 1 by the use of the code generation hooks. Pretty neat feature.

Bullet 2. still is an issue though.

**Comment by masseelch** [comment]
@a8m I am sorry to ping you here, but did this somehow slip through? Do you need more info?

**Comment by a8m** [comment]
Hey @masseelch and sorry for the delay. I faced this issue before (bullet 2), but needed some time to think about it.

The proposed solution (that I'm working on), is to use a naming convention for "helper templates". Unlike "root templates", "helper templates" are not executed directly by Ent and won't be written to a file, but can be used internally by other templates. 

A template is treated as a helper template, if its name follows the format: `<root-template>/helper/.+`. For example:

-  For a root template `foo`, a helper can be defined as `foo/helper/bar`.
-  For a root template `foo/bar`, a helper can be defined as `foo/bar/helper/baz`.
 
Let's in a file named `foo.tmpl`, you have 2 templates, 1) `foo` and 2) `foo/helper/bar`, the result will be a file named `foo.go`.

```
{{ define "foo" }}
    {{ template "foo/helper/bar" . }}
    // ...
{{ end }}

{{ define "foo/helper/bar" }}
 // ..
{{ end }}
```

I was thinking about using the word `internal` instead of `helper` at the beginning but realized it will introduce a limitation to generate [`internal` Go packages](https://golang.org/doc/go1.4#internalpackages). 

Another idea I had in mind is to add parser directives (similar to the [Go compiler directives](https://pkg.go.dev/cmd/compile#hdr-Compiler_Directives)), but wasn't sure it's a better approach, so your feedback is more than welcome here:

```
{{ define "foo" }}
    {{ template "foo/helper/bar" . }}
    // ...
{{ end }}

{{/* gotemplate:noroot */}
{{ define "foo/helper/bar" }}
 // ..
{{ end }}
```

[elk](https://github.com/masseelch/elk) looks super cool btw 😉 

cc @rotemtam, @zeevmoney

**Comment by masseelch** [comment]
Hey @a8m, thanks for taking the time to look at this.

Solution 1 looks good to me, just was wondering about the following: Why the need for `<root-template/helper/.+` and not simply `helper/.+` or `.*/helper/.+`?

The current proposal will prevent the use of helpers across multiple `<root-templates>`s, at least this is what I get from it.

Compiler directives are used to have some kind of conditional compilation for files. If we'd wanted to sometimes include a template and sometimes don't, I'd say the second proposal is a valid approach. In this case I do like the first proposal more, tbh.

**Comment by a8m** [comment]
> Solution 1 looks good to me, just was wondering about the following: Why the need for `<root-template/helper/.+` and not simply `helper/.+` or `.*/helper/.+`? Are you planning to allow helper templates in its own files?
>
> The current proposal will prevent the use of helpers across multiple <root-templates>s, at least this is what I get from it.

We can support this as well. 

>  In this case I do like the first proposal more, tbh.

So did I. I'll send a patch soon, and add you as a reviewer.

**Comment by masseelch** [comment]
Thank you very much :+1:

**Comment by a8m** [comment]
@masseelch, please see #1742. 

Just raising here another approach I had in mind, similar to the [testing.T.Helper](https://pkg.go.dev/testing#T.Helper) function:

```
{{ define "boring" }}
{{ helper }} // Calling the "helper" function, will make this template a helper template. 

// ...
{{ end }}
```

**Comment by masseelch** [comment]
> ```
> {{ define "boring" }}
> {{ helper }} // Calling the "helper" function, will make this template a helper template. 
> 
> // ...
> {{ end }}
> ```

I am not sure I'd like that. I am usually trying to avoid side effects whereever possible. But with this approach we'd be able to have `ent` generate a `helper.go`, which is not possible with the current proposal (which is not really an issue, honestly
).

**Comment by a8m** [comment]
You'll be able to generate `helper.go` with the current proposal. The matching in #1742, is on:

```go
case strings.HasPrefix(name, "helper/"):
case strings.Contains(name, "/helper/"):
```

**Comment by masseelch** [comment]
You are right. Have not reviewed yet. Will do soon.
