### ISSUE TITLE
UUID Nillable does not generate SetNillableUUID

### ISSUE THREAD

**Issue by maxifom** [ent/ent#1681]
In #1504 we got .Nillable() support for uuid builder. But when code is generated, there is no method to Set uuid field to nil.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

`go generate ./...` doesn't produce SetNillableUUID method

## Expected Behavior 🤔

`go generate ./...` produces SetNillableUUID method

## Steps to Reproduce 🕹

Reproduction repo: https://github.com/maxifom/ent-uuid

Steps that i used to get to ent-uuid repo state:

1. `go get entgo.io/ent/cmd/ent@master`
2. `go run entgo.io/ent/cmd/ent init User`
3. Add my_uuid field of type UUID and Optional + Nillable
4. `go mod vendor`
4. `go generate ./...`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.16.5  |
| Ent         | v0.8.1-0.20210703051936-d1c44ef0cb53   |
| Database    | None   |
| Driver      | None |

**Comment by a8m** [comment]
Hey @maxifom, and thanks for opening this issue.

As mentioned in the doc, the `Nillable` option is used to distinguish between the zero value of fields and `nil`; for example, if the database column contains `0` or `NULL`. The `Nillable` option exists exactly for this.
If you have an Optional field of type `T`, setting it to `Nillable` will generate a struct field with type `*T`. Hence, if the database returns `NULL` for this field, the struct field will be `nil`. Otherwise, it will contain a pointer to the actual data.

> there is no method to Set uuid field to nil.

Each optional field has a `Clear<Field>` method that sets the field to `NULL` in the database (use this one!).

The `SetNillable<Field>` is different, it sets the provided value if it's not `nil`. This is useful for users to skip `nil` checks before calling setters (e.g. map optional GraphQL fields to Ent fields).

Fields with Go types that can be assigned to `nil` (like slice or pointer), don't have this option, because the following call is valid:

```go
c.SetUUID(nil) // uuid.UUID(nil)
```

Closing, but please reopen if have more questions or join our [Slack channel](https://entgo.io/docs/slack/). Thanks
