### ISSUE TITLE
not return those field in query whose default value is false, empty string 

### ISSUE THREAD

**Issue by harshmangalam** [ent/ent#1749]
I have query my user data and get all data but those field are not  included whose default value was null, "" or false

json data when i have toggled is_active from false to true during login

```json
{
        "id": 1,
        "name": "Harsh Mangalam",
        "username": "harshmangalam",
        "gender": "male",
        "role": "user",
        "is_active": true,
        "created_at": "2021-07-20T08:31:54.667045+05:30",
        "updated_at": "2021-07-20T13:18:54.199194+05:30",
        "edges": {}
    }
```

after some time json data when i have toggled is_active from true to false during logout

```json
{
        "id": 1,
        "name": "Harsh Mangalam",
        "username": "harshmangalam",
        "gender": "male",
        "role": "user",
        "created_at": "2021-07-20T08:31:54.667045+05:30",
        "updated_at": "2021-07-20T13:09:52.705781+05:30",
        "edges": {}
    }
```

| Tech        | Version |
| ----------- | ------- |
| Go          | go1.16.6 linux/amd64 |
| Ent         |  v0.8.0    |
| Database    | Postgresql   |
| Driver      | https:/github.com/lib/pq       |

**Comment by rotemtam** [comment]
Hi @harshmangalam ,
Thanks for reaching out.
I'm not sure I understand what your question is. Can you elaborate? 

What you described is expected behavior from `json.Marshal` for struct fields annotated with `omitempty`.
If you look at the structs generated by ent, by default, fields are tagged with `omitempty`:
https://github.com/ent/ent/blob/279d6c2a123e786cde54218caca9ee9c66c21b76/entc/integration/customid/ent/doc.go#L19-L29

This behavior is described in [the godoc for the json package](https://pkg.go.dev/encoding/json#Marshal).

To control struct tags in the generated code, you can use the [StructTag](https://entgo.io/docs/schema-fields/#struct-tags) modifier when defining your ent schema.

**Comment by y4code** [comment]
I have the same problem with @harshmangalam 

so is there any general way to remove the tag `omitempty`, `Annotations()` or `StructTags` works, but not so simple and clean

**Comment by rotemtam** [comment]
Hi @y4code,

If you want to apply a general manipulation to all schemas, you can use [Codegen hooks](https://entgo.io/docs/code-gen#code-generation-hooks) to mutate the graph before code is generated. Does this answer your question?

**Comment by y4code** [comment]
@rotemtam Thanks, seems like using `Hooks` with `entc` works fine

If I want to remove `omitempty` with `ent CLI`,  should i write a feature flag which would be used like this ?
```shell
go run entgo.io/ent/cmd/ent generate --feature noomitempty ./ent/schema
```

**Comment by y4code** [comment]
> @rotemtam Thanks, seems like using `Hooks` with `entc` works fine
> 
> If I want to remove `omitempty` with `ent CLI`, should i write a feature flag which would be used like this ?
> 
> ```shell
> go run entgo.io/ent/cmd/ent generate --feature noomitempty ./ent/schema
> ```

Use external templates instead of feature flag, I figured it out, thanks @rotemtam

**Comment by rotemtam** [comment]
Ok, sounds great. A feature flag for this is indeed a bit overkill :-)

Closing this. Let me know if you need any other assistance.

If you haven't signed up for [our newsletter](https://www.getrevue.co/profile/ent), you can subscribe to updates and great content about ent.
