### ISSUE TITLE
Is it possible to set Nillable in the Time field with using gRPC?

### ISSUE THREAD

**Issue by tochukaso** [ent/ent#1780]
I am using Ent for creating schema and gRPC.

I want to set `Nillable` in the time field.

My code is below.

schema/shop.go
``` go 
// Fields of the Shop.
func (Shop) Fields() []ent.Field {
	return []ent.Field{
		field.Time("deleted_at").Optional().Nillable().
			Annotations(entproto.Field(2)),
	}
}

func (Shop) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entproto.Message(),
		entproto.Service(),
	}
}
```

And run command ` go generate ./...`

generated file
entpb_shop_service.go

``` go

func toProtoShop(e *ent.Shop) (*Shop, error) {
	v := &Shop{}
	deletedat := timestamppb.New(e.DeletedAt)
	v.DeletedAt = deletedat
	id := int32(e.ID)
	v.Id = id
	return v, nil
}

```

There is a compile error at `timestamppb.New (e.DeletedAt)`.
Because `e.DeletedAt` is pointer.

Is it possible to set Nillable in the Time field with using gRPC?

**Comment by rotemtam** [comment]
hey @tochukaso ,
Thanks for reaching out. 

We don't have support for nillable fields currently.
If you don't particularly need DeletedAt to be a pointer field you can use just `.Optional` to make the field nullable in the DB.

It shouldn't be a difficult fix. Is this something you'd like to contribute? Otherwise, I can allocate some time to fix it next week.

**Comment by rotemtam** [comment]
If you want to work on this, please reach out to me via [Slack](https://entgo.io/docs/slack) and I'll guide you through it.
