### ISSUE TITLE
add version command for ent

### ISSUE THREAD

**Issue by godcong** [ent/ent#1828]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The current ent command line tool cannot view the version

## Motivation 🔦

I'm using ent's bin file, although I always use it.
But after a while I still forgot its version.
I hope to add a command to view the version in the ent command.

**Comment by a8m** [comment]
Hey @godcong and thanks for proposing this. This was proposed a few times and was rejected because the current Go tool chain already solves this issue. See my answer at https://github.com/ent/ent/issues/368#issuecomment-591912949:

> What's wrong with `go version -m <binary>`?
> 
> I also prefer users to use `go generate` and not `ent` directly, for the reason [mentioned here](https://entgo.io/docs/code-gen/#version-compatibility-between-entc-and-ent). Especially now, when modules support is ready for production use (since Go 1.14).

In short, users should not deal with `ent` CLI directly. Instead, they use `go run entgo.io/ent/cmd/ent`. When using `go run` from a Go module project, Go executes the `ent` binary with the version mentioned in the `go.mod` file. This way, you're making sure the Ent version (used at runtime) is identical to the version that was used to generate the assets (with `go generate`).

Please, let me know if I can close the issue. Thanks

**Comment by godcong** [comment]
ok.
I will say if I find any problems.
