### ISSUE TITLE
Question: what is role.Unknown?

### ISSUE THREAD

**Issue by maxifom** [ent/ent#1840]
On page https://entgo.io/docs/schema-fields/#go-type I found this code: 
![image](https://user-images.githubusercontent.com/20924207/129471485-41a65d66-cc61-4b19-8d3b-84de65746ff9.png)

What is role.Unknown?

Also is the documentation correct? As of 0.9 enumBuilder requires EnumValues interface to be implemented for GoType, but as I guess role.Unknown is some kind of string enum

**Comment by zeevmoney** [comment]
Hey @maxifom, `role.Unknown` represents a `const` with a type that implements the `EnumValues` interface. It can be a based on a string as you said, but the point is that it still implements the `EnumValues` interface.
An example of such type can be the following:

```go
const (
	Unknown Role = "UNKNOWN"
	Admin   Role = "ADMIN"
	Owner   Role = "OWNER"
	User    Role = "USER"
	Read    Role = "READ"
	Write   Role = "WRITE"
)

func (Role) Values() (roles []string) {
	for _, r := range []Role{Admin, Owner, User, Read, Write, Unknown} {
		roles = append(roles, string(r))
	}
	return
}
```

`GoType()` accepts an "instance" of a `role.Role` object, since there's no way to pass only the type (e.g. `GoType(role.Role)`). The following code is also valid:

```go
field.Enum("role").
	GoType(role.Role(""))
```

**Comment by a8m** [comment]
Thanks for helping @zeevmoney.

Closing, but please feel free to send a patch to improve the docs. Thanks 🙏
