### ISSUE TITLE
How to use full-text index for query?

### ISSUE THREAD

**Issue by kilogi** [ent/ent#2122]
I created a full-text index for a field, how should I use it in ent?
I didn't find the function of how to use full-text index in ent

**Comment by a8m** [comment]
Hey @kilogi and thanks for raising up this issue.

What database do you use? Can you please paste here the SQL statements/queries you'd like to execute with ent?

**Comment by kilogi** [comment]
> Hey @kilogi and thanks for raising up this issue.
> 
> What database do you use? Can you please paste here the SQL statements/queries you'd like to execute with ent?

Database is postgres.
sql statement like this “select title from posts where tsv_content @@ plainto_tsquery('hello world')”

**Comment by kilogi** [comment]
The type of tsv_content field is tsvector and its index type is gin

**Comment by nilpntr** [comment]
How did u managed to create the index?

**Comment by a8m** [comment]
Hey! Just to follow up on this issue:

1\. In case there's a need to create a `FULLTEXT` index, please use [Atlas Annotation](https://entgo.io/docs/schema-indexes#atlas-support) in your index definition:
```go
func (User) Indexes() []ent.Index {
    return []ent.Index{
        index.Fields("c4").
            Annotations(entsql.IndexType("HASH")),
        // Enable FULLTEXT search on MySQL,
        // and GIN on PostgreSQL.
        index.Fields("c5").
            Annotations(
                entsql.IndexTypes(map[string]string{
                    dialect.MySQL:    "FULLTEXT",
                    dialect.Postgres: "GIN",
                }),
            ),
    }
}
```

2\. In order to inject custom predicates or modifiers to queries, please see:
- https://entgo.io/docs/predicates#custom-predicates
- https://entgo.io/docs/feature-flags#custom-sql-modifiers

Closing, but I'm available in our [Discord server](https://discord.gg/qZmPgTE6RX) for any question. Thanks 🙏
