### ISSUE TITLE
How to write ON CONFLICT WHERE clause using time.Time?

### ISSUE THREAD

**Issue by ivanstanev** [ent/ent#2126]
Hey,

I have a query that tries to update column on upsert using a WHERE clause as follows:

```go
client.Object.Create().
    SetPublicId(publicId).
    SetDigest(digest).
    SetTime(*timestamp). // type *time.Time
    OnConflict(
	    sql.ConflictColumns(object.FieldPublicId, object.FieldDigest),
	    sql.ConflictWhere(
		    sql.LT(object.FieldTime, timestamp),
	    ),
    ).
    UpdateTime().
    Exec(context)
```

The problem is that the WHERE clause doesn't seem to work - no matter what the timestamp looks like, it always gets updated as if the `LT` is not working. Here is the payload that I'm sending:

```json
{
  "publicId": "65581f75-4cec-4ae5-9d12-aedde47a97ac",
  "digest": "sha256:1e6c2f411e9ca05be01400d4c7436b4e3fa693ee71da4418a122d1aa0c270e25",
  "time": "2021-11-11T10:01:47.458Z"
}
```

Could you advise how the `LT` should be used?

**Comment by a8m** [comment]
Hey @ivanstanev 👋, what database do you use?

**Comment by ivanstanev** [comment]
Hey @a8m, using Postgres

**Comment by a8m** [comment]
OK, I found the issue. It's not your fault. The generated query is not correct, as the `WHERE` clause should be appended after `UPDATE SET`. Thanks for reporting this and I'll send a patch soon 🙏

**Comment by a8m** [comment]
Hey @ivanstanev, please see https://github.com/ent/ent/pull/2131 as a fix. The problem was different from what I mentioned above,  but it was solved and you can see a test case for it in the mentioned PR. Note, you need to use `sql.UpdateWhere` instead of `sql.ConflictWhere` in your query in order to make it work because the 2 are different. 

Closing. Please, update to latest master (`go get entgo.io/ent/cmd/ent@master`) and reopen if you still have issues with it. Thanks again for the report.

**Comment by ivanstanev** [comment]
@a8m Thank you for the quick response!
