### ISSUE TITLE
Feature Request: Set `imports.LocalPrefix` when sort imports

### ISSUE THREAD

**Issue by Thearas** [ent/ent#2170]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Sames as `goimports -local "<my-pkg>/ent"`.

## Motivation 🔦

Current:

```go
import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"<my-pkg>/ent/internal"
	"<my-pkg>/ent/predicate"
	"<my-pkg>/ent/testbed"
)
```

What I want:

```go
import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"

	"<my-pkg>/ent/internal"
	"<my-pkg>/ent/predicate"
	"<my-pkg>/ent/testbed"
)
```

We could set `imports.LocalPrefix` to `graph.Config.Package`.

**Comment by a8m** [comment]
Hey @Thearas, and thanks for the suggestion!

TBH, I don't think a new flag or option is needed, because the same functionality can be achieved today. If you're using the `ent/entc.go`-based config option, the `LocalPrefix` can be set before running codegen:

```go
//go:build ignore

package main

// ...

func main() {
	imports.LocalPrefix = "<config-goes-here>"
	// ...
	err = entc.Generate("./schema", &gen.Config{}, opts...)
	if err != nil {
		log.Fatalf("running ent codegen: %v", err)
	}
}
```

If you're using the command line version (that is executed by `go generate`), you can just add another line for executing `goimports` after `ent generate`. 

```go
package ent

//go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./schema
//go:generate go run -mod=mod golang.org/x/tools/cmd/goimports -local <config-goes-here> -w .
```

**Comment by masseelch** [comment]
> ```go
> //go:build ignore
> 
> package main
> 
> // ...
> 
> func main() {
> 	imports.LocalPrefix = "<config-goes-here>"
> 	// ...
> 	err = entc.Generate("./schema", &gen.Config{}, opts...)
> 	if err != nil {
> 		log.Fatalf("running ent codegen: %v", err)
> 	}
> }
> ```

One cool thing so far about `entc` is, that it works for every module regardles of its name. In the proposal above I have to change it for every new module (so there is boilerplate added ;-)).

> If you're using the command line version (that is executed by `go generate`), you can just add another line for executing `goimports` after `ent generate`.
> 
> ```go
> package ent
> 
> //go:generate go run -mod=mod entgo.io/ent/cmd/ent generate ./schema
> //go:generate go run -mod=mod golang.org/x/tools/cmd/goimports -local <config-goes-here> -w .
> ```

This feels unclean. Because the first line already calls `goimports` it runs twice. 

Overall: I think this _beautifies_ the code generated by Ent and it is not a BC. It just changes the import sort order. If you have concerns about the noise in version history we can make this configurable by some configuration. But I really like this.

**Comment by a8m** [comment]
We're using the second option for running `goimports` (with `local`) to apply the same formatting on all project files (including generated assets), and not only ent assets.

```
goimports -w -local golang.org,entgo.io,github.com,ariga.io .
```

**Comment by masseelch** [comment]
Hmm. Okay :unicorn:

**Comment by a8m** [comment]
kk, I just figured out I read this proposal incorrectly. This issue proposes just calling goimprots with `LocalPrefix` with the generated package and not about configuring the `LocalPrefix`. So, that makes sense. But, but I think you want to group imports by the "root" package and not by generated `ent` package, right?

**Comment by a8m** [comment]
See https://github.com/ent/ent/pull/2171/files#r757553535

**Comment by Thearas** [comment]
> Hey @Thearas, and thanks for the suggestion!
> 
> TBH, I don't think a new flag or option is needed, because the same functionality can be achieved today. If you're using the `ent/entc.go`-based config option, the `LocalPrefix` can be set before running codegen:
> 
> ```go
> //go:build ignore
> 
> package main
> 
> // ...
> 
> func main() {
> 	imports.LocalPrefix = "<config-goes-here>"
> 	// ...
> 	err = entc.Generate("./schema", &gen.Config{}, opts...)
> 	if err != nil {
> 		log.Fatalf("running ent codegen: %v", err)
> 	}
> }
> ```

Close with the solution👆🏻.
