### ISSUE TITLE
query count should return int64 ?

### ISSUE THREAD

**Issue by shenghui0779** [ent/ent#2213]
![image](https://user-images.githubusercontent.com/67535398/145662891-843b68ba-c53e-46c1-8592-4d0bfc4d947f.png)

**Comment by a8m** [comment]
Hey @shenghui0779 👋 
It does make sense that `Count` will return `uint64` instead of `int`, but we can't change the API atm, and you're welcome to override this part using [custom template](https://entgo.io/docs/templates/) if it cause you any issues. Also, I think most (if not all) ent users use 64-bits systems, and `int` has the range of int64, so using `int` is safe and also reduce redundant conversions. 

Closing, but please feel free to continue the discussion or join our [Slack](https://entgo.io/docs/slack/)/[Discord](https://discord.gg/qZmPgTE6RX) if you have more questions/thoughts. Thanks 🙏
