### ISSUE TITLE
How can I use a  sql file to initialize a schema template file

### ISSUE THREAD

**Issue by brave-orange** [ent/ent#2291]
Because i have a lot of table ,so I had to wirte all fields in the schema templates file；

do you have other faster way ?

**Comment by zeevmoney** [comment]
Hi @brave-orange,

There is a project I've been working on lately called `entimport`: https://github.com/ariga/entimport
You can use it to import your SQL DB (Postgres and MySQL are currently supported) to an ent schema.
Since it's fairly new there are some limitations, so you are welcome to open an pr/issue there if you have any problem or request.

**Comment by brave-orange** [comment]
Awsome!!! I will try !

**Comment by zeevmoney** [comment]
@brave-orange is there anything else I can help you with, or we can close this issue?
