### ISSUE TITLE
How to set up security to block unconditional updates and deletes

### ISSUE THREAD

**Issue by superwy** [ent/ent#2344]
How to set up security to block unconditional updates and deletes.   
Avoid updating or deleting all data

**Comment by a8m** [comment]
Hey @superwy and thanks for opening this issue 👋 

If you want to block all bulk update/delete operations you can use `Hooks`/`Privacy` to achieve this. We actually used this to allow only delete/update by specific id, as the `Where` clause can be a tautology and update or delete all rows. For example:

```go
// Using privacy.
privacy.DenyMutationOperationRule(ent.OpUpdate | ent.OpDelete)

// Using hooks.
hook.Reject(ent.OpUpdate | ent.OpDelete)
```

Both options can be shared across all schemas using an [ent.Mixin](https://entgo.io/docs/schema-mixin).

Let me know if it does answer your question, if you like to add it to our [FAQ page](https://entgo.io/docs/faq), or you need more assistance here.

**Comment by superwy** [comment]
I want to use like this：
`EntClient.AdminRole.Delete().Where(adminrole.IDIn(1, 2 ,3)).Exec(ctx)`

deny like this:  
`EntClient.AdminRole.Delete().Exec(ctx)`

because there is no where condition，will delete all data.
It's a dangerous operation, but I don't want to disable deletion of multiple pieces of data, I just want to disable deletion of all data.

@a8m

**Comment by crossworth** [comment]
I think I have a solution @superwy, it requires templates and hooks.

When using a [runtime hook](https://entgo.io/docs/hooks#runtime-hooks), we get a `ent.Mutation`, that contains (a concrete type with) a slice of unexported predicates, we need to get access to it, so we create a [template](https://entgo.io/docs/templates/).

```go
{{/* gotype: entgo.io/ent/entc/gen.Graph */}}
{{ define "getpredicates" }}
    {{ $pkg := base $.Config.Package }}
    {{ template "header" $ }}

    {{ range $n := $.Nodes }}
        {{ $mutation := $n.MutationName }}
        // HasPredicates returns if the mutation has predicates defined.
        func (m {{ $mutation }}) HasPredicates() bool {
            return len(m.predicates) > 0
        }
    {{ end }}
{{ end }}
```
The template above will generate another method on the Mutations called `HasPredicates() bool` that returns if the mutation has predicates or not, we cannot return the predicates since they are `predicate.Type` and that would make the next part hard to handle.

Next we create a runtime hook like this.
```go
func SecurityHook() ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			hp, ok := m.(interface{ HasPredicates() bool })
			if !ok {
				return nil, fmt.Errorf("type dont implement HasPredicates")
			}

			if !hp.HasPredicates()  {
				return nil, fmt.Errorf("no predicates found")
			}

			return next.Mutate(ctx, m)
		}
	}
}
```

Does this work for you?
