### ISSUE TITLE
can ent auto ignore the field which is zero value when update ?

### ISSUE THREAD

**Issue by phostann** [ent/ent#2519]
eg:

ent.User.UpdateOneID(1).SetPassword("").SetRole(2).Save(context.Background())

I mean that can ent auto ignore password field ?

some one can tell me about this? Thank you in advance.

**Comment by a8m** [comment]
Hey @phostann 👋 

I assume the reason you update this field with zero value, is because it's optional in your API layer (or in GraphQL mutation). However, Ent can't distinguish between zero/real values when updating empty fields. This is why the explicit setter was created unlike other approaches mentioned in the [doc](https://entgo.io/docs/faq#how-to-create-an-entity-from-a-struct-t).

The workaround for this is to use a pointer (to string) in your API layer and call the `SetNillablePassword` option when updating. This way, you can explicitly and correctly distinguish between real and zero values. The `SetNillablePassword` option will just save you the `if body.Password != nil` check in the handler/resolver.


Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need more help with this 😎

**Comment by phostann** [comment]
@a8m Thank you for your answer, *string works for me perfectly.
