### ISSUE TITLE
Q: How to set config manually

### ISSUE THREAD

**Issue by medivh-jay** [ent/ent#2529]
Hello, I serialized the result data of ENT query, when I deserialize, I will not be able to do more with this deserialized object, Because the private attribute `config` in the object is already a nil, so I want to ask how to manually set config after deserialization.
Thank you.

example:
```
// Member is the model entity for the Member schema.
type Member struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,string"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// UID holds the value of the "uid" field.
	UID uint `json:"uid,omitempty"`
	// RegisterAt holds the value of the "register_at" field.
	RegisterAt uint `json:"register_at,omitempty"`
	Edges        MemberEdges `json:"edges"`
	hierarchy_id *uint64
}
```

**Comment by a8m** [comment]
Hey @medivh-jay 👋 
There's no way to instantiate an entity manually because the `config` contains internal information like a database or transaction connection. However, if you still want to do it, you can use [external templates](https://entgo.io/docs/templates/) to extend the generated entities and export a function like `Instantiate(c *Client)`. This will give you the freedom to set the `config` field based on your needs:

```go
var m ent.Member
// Unmarshal.
m.Instantiate(c)

// Use m.
m.QueryFriends().All(ctx)
```

Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) if you still need help with this issue 😃
