### ISSUE TITLE
Select(): Result should contain only selected fields

### ISSUE THREAD

**Issue by stonymahony** [ent/ent#2553]
When using Select(), only the specified fields are actually loaded, so far so good. 

But I would expect the struct to contain only the fields that I have selected , but this is not the case. 
Instead, the fields that are not selected and loaded are populated with default values. 

This has several disadvantages:
- reveals which fields the entity has
- unnecessarily large payload
- confusion for the recipient, as it is not immediately obvious which fields contain real values and which only contain nonsense

Example:

Entity "user"
```
func (User) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.NewV4()).Immutable().
			Annotations(&entsql.Annotation{
				Default: "gen_random_uuid()",
			}),
		field.UUID("tenantId", uuid.NewV4()).StorageKey("tenantId"),
		field.String("email"),
		field.String("username"),
		field.Time("createdAt").StorageKey("createdAt").Immutable(),
		field.Time("updatedAt").StorageKey("updatedAt"),
	}
}
```

Generated struct "user"

```
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantId holds the value of the "tenantId" field.
	TenantId uuid.UUID `json:"tenantId,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges UserEdges `json:"edges"`
}
```

Query with Select()

`user, err := db.User.Query().Where(userId).Select(user.FieldUsername).First(context.Background())`

Expectation (serialized as JSON)

```
{
  "username": "john_doe"
}

```

Actual result

```
{
            "id": "164250b3-3a39-4b36-9428-c03a0d23f26d",
            "tenantId": "00000000-0000-0000-0000-000000000000",
            "username": "john_doe",
            "createdAt": "0001-01-01T00:00:00Z",
            "updatedAt": "0001-01-01T00:00:00Z",
            "edges": {}
          }

```

The generated struct has the "omitempty" tags for the JSON serialisation, but since the values are not empty, but have the default values, they are of no effect.

Is there currently already a solution for this? Otherwise, is there a possibility to develop such a feature?
Thanks!

**Comment by a8m** [comment]
Hey @stonymahony and thanks for opening this issue 👋 

Unfortunately, there's no simple way to configure this behavior using `json` tags. If the fields were `Nillable`, their types were pointers and you could achieve the expected behavior without code changes. However, that's not the case and I don't think the codec layer should affect the table structure. 

What are my proposed solutions?
1. If you have more than 1-2 types that suffer from this issue, you can extend the generated entity types and implement a custom [json.Marshaler](https://pkg.go.dev/encoding/json#Marshaler) for all/some of them using [external templates](https://entgo.io/docs/templates/).
2. Another option, is to create a temporary struct type (in your resolver/handler) with pointer type on the fields, copy the fields and call `json.Marshal` with it. 

https://github.com/golang/go/issues/45669 may solve the issue for `time.Time` fields but there's no easy fix for the UUID type besides comparing with [`uuid.Nil`](https://pkg.go.dev/github.com/google/uuid#pkg-variables) and that's too specific.

Closing, but please feel free to reopen or join our [Discord server](https://discord.gg/qZmPgTE6RX) to discuss options for solving this automatically with clean API. Thanks

**Comment by stonymahony** [comment]
Hey @a8m, thanks for your quick reply!

I had already feared that the sticking point lies more in Go and encoding/json than in entgo.

Thanks to your input, I have come across a whole bunch of issues requesting such functionality (omitnil/omitempty incl. default values), so far in vain. Of course, that would be the cleanest and simplest solution, but I guess we'll just have to wait and see...

For entities where the omission is urgent, I will probably use external templates, thanks for the hint and this awesome library!

**Comment by a8m** [comment]
Thanks for the kind words @stonymahony and please don't hesitate to ping me on Discord if you need any help with templates ❤️

**Comment by a8m** [comment]
For future readers, please see https://entgo.io/docs/schema-fields#nillable-required-fields.
