### ISSUE TITLE
[FR] Log already "composed" queries instead of "naked" ones

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2605]
## Summary 💡

I would like to have from `client.Debug()` already "composed" queries instead of the naked query with args.

## Motivation 🔦

It is very slow to debug any queries (especially if very long) directly by copying and pasting in the DB because I have to manually replace the args that are logged separately.

Is there an easier way? Am I wrong going this way?

Example:

- right now:

```
query=INSERT INTO "players" ("created_at", "name", "tenant_id") VALUES ($1, $2, $3) RETURNING "id" args=[2022-06-04 10:48:33.5307582 John 3]
```

- expected:

```
query=INSERT INTO "players" ("created_at", "name", "tenant_id") VALUES ('2022-06-04 10:48:33.5307582', 'John', '3') RETURNING "id"
```

_Thanks._

**Comment by a8m** [comment]
Hey! Ent cannot implement this logic in its logging driver, because it cannot be done with simple replacing and requires a lot of (sensitive) code for each dialect to make it right (we cannot assume users won't copy/paste and use these statements). See [MySQL interpolateParams](https://github.com/go-sql-driver/mysql/blob/bcc459a906419e2890a50fc2c99ea6dd927a88f2/connection.go#L198-L295) as an example. 

I think it's out of the scope of the `DebugDriver`, and the solution for custom logging features like this is explained here - https://github.com/ent/ent/issues/2604#issuecomment-1146792428

**Comment by a8m** [comment]
Closing as there are no action items to take here. Please, let me know if you need any help with writing such a logger. Thanks 🙏
