### ISSUE TITLE
Whether there are plans for generic support

### ISSUE THREAD

**Issue by godcong** [ent/ent#2683]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Motivation 🔦

1. much of the code is now not reusable.
2. the same code cannot be accessed through a unified interface due to different types.
3. I want to add some generic methods for ent.

**Comment by a8m** [comment]
Hey @godcong and it's great to see you here again 👋 

We plan to publish a proper roadmap for v0.12 after releasing v0.11 (really soon). In v0.12, we'll start experimenting with generics, and mainly work on reducing the amount of the generated code. I'll update the issue after v0.11 is released and you're welcome to join our Discord server as we may discuss some ideas and thoughts there while working on it.

Closing because there's no action to take here. Thanks 🙏
