### ISSUE TITLE
No PG schema change with `.Annotations(entsql.Annotation{Size})` or `.MaxLen()`

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2712]
## Current Behavior 😯

Using:

```go
field.String("name").Annotations(entsql.Annotation{Size: 160})
```

or:

```go
field.String("name").MaxLen(160)
```

my DB schema is:

```sql
name character varying NOT NULL
```

## Expected Behavior 🤔

I expect:

```sql
name character varying(160) NOT NULL
```

Am I wrong?

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.18.3  |
| Ent         | entgo.io/contrib v0.2.1-0.20220629201726-e738ef866e51, 	entgo.io/ent v0.10.2-0.20220701203018-4f7b1739cdd3   |
| Database    | PG   |
| Driver      | pgx        |

**Comment by a8m** [comment]
Hey @frederikhors and thanks for opening this issue. We actually discussed this issue on Discord a week or two ago.

The reason we didn't implement it in PostgreSQL is because it does not improve performance. See:

![image](https://user-images.githubusercontent.com/7413593/177040858-0acbac24-68af-4454-815f-6f7348abc6f4.png)

However, in case you really need it, we can add support for it in Atlas. The [patch](https://github.com/ent/ent/blob/master/dialect/sql/schema/postgres.go#L716-L719) is really simple, so you're welcome to contribute it or one of the team can handle this. See

**Comment by frederikhors** [comment]
Ok. It was for performances reasons. Thanks.
