### ISSUE TITLE
`empty predicate PlayerWhereInput: field 'or'`

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2725]
I'm having an issue similar to https://github.com/ent/ent/issues/2673.

From one javascript client I'm requesting this:

```json
{
  "input": {
    "where": { "or": [{}, {}] }
  }
}
```

because the code on the client is roughly:

```js
where: {
  or: [
    { playerNameContainsFold: searchText },
    { teamContainsFold: searchText },
  ],
  // and many others
}
```

and `searchText` is dynamic and can be `undefined`: is very easy to write the code like that.

Ent throws with:

```
error="ent: empty predicate PlayerWhereInput: field 'or'"
```

Can we avoid this error?

**Comment by a8m** [comment]
Hey @frederikhors 👋 

> Can we avoid this error?

This is actually an invalid predicate and we can't accept it. All errors from `<T>WhereInput.Filter` are validation errors (e.g empty `or`, or empty `and`). If you don't care about these validations, you can ignore them.

**Comment by frederikhors** [comment]
> If you don't care about these validations, you can ignore them.

Can you show me how?

**Comment by frederikhors** [comment]
Please?

**Comment by a8m** [comment]
Yes, because the inverse is not possible. e.g. I don't want to allow these types of predicates in my applications and I rely on Ent to do these validations. However, if someone doesn't care about these validations, they can just ignore these errors.
In case we ignore these validations, users who care about them (like me) won't be able to catch them in their product. 

> Can you show me how, please?

```go
// q is a <T>Query.
if fq, err := input.Filter(q); err == nil {
    q = fq
}
return q.All(ctx)
```
