### ISSUE TITLE
[FR?] Order by edge field using `entgql`'s `.With[TYPE]()`

### ISSUE THREAD

**Issue by frederikhors** [ent/ent#2807]
Given this schema:

```go
func (Player) Fields() []ent.Field {
  return []ent.Field{
    field.String("name"),
    field.Int("age").Annotations(entgql.OrderField("AGE")),
  }
}

func (Player) Edges() []ent.Edge {
  return []ent.Edge{
    edge.To("team", Team.Type).Required(),
  }
}
```

Can I order `Player` by `Team.Name`?

I know [I can edge order](https://entgo.io/docs/paging#edge-ordering) `Player` but I'm using this code with entgql:

```go
output, err := query.Paginate(ctx,
  After,
  First,
  Before,
  Last,
  ent.WithPlayerOrder(Order),
  ent.WithPlayerFilter(Filter),
)
```

and I don't know if/how to do.

**Comment by syssam** [comment]
@a8m any solution with that...?

**Comment by a8m** [comment]
Hey @frederikhors and sorry for the delay. @giautm and I discussed this internally, and don't have a final design for it. We have a few open questions/thoughts at the moment and we'll love to hear your feedback before we continue to the implementation. 

We prefer that the API will be added to Ent (natively) and `entgql` will just use it. Same as we implemented aliases. The API I thought about is quite similar to what I wrote a year ago (https://github.com/ent/ent/issues/1330):
```go
// For unique edges, generate static API for sorting by relation/edge fields.
client.Pet.Query().
  Order(
    user.ByOwnerName(),
    user.ByName(),
  ).
  All(ctx)

// For non-unique edges, generate order functions for sorting
// by relation/edge count. We skip generating order functions
// for the rest of the fields, as a user row can be associated
// with more than one post.
client.User.Query().
  Order(
    user.ByName(),
    user.ByPostsCount(),
  ).
  All(ctx)

// Skip generating order functions for more than one level,
// but users can still use the same "custom API" for writing
// more specific queries.
client.User.Query().
  Order(
    user.ByName(),
    user.ByPosts(func(s *sql.Selector) {
      // Custom order on the join-table goes here.
    }),
    func(s *sql.Selector) {
      // Custom order on the root query goes here.
    }
  ).
  All(ctx)
``` 

For the `entgql` and GraphQL we need to accept the `Order` annotation on edges and change the `<T>Order` type to accept more than one field (and edge fields). This is not really necessary for edge-ordering, but if we already touch it, we should do all necessary changes.

**Comment by frederikhors** [comment]
I really like how it's coming. Maybe I can try it out as soon as it's ready in a git branch.

Thanks!

**Comment by syssam** [comment]
@a8m we more focus on the Relay Cursor Connections (Pagination).
We know we can do that without a relay cursor, follow https://entgo.io/docs/paging#custom-ordering.
However, I can't find any solution with Relay Cursor because the code is generated by ent and private.

**Comment by kurtinge** [comment]
This API suggestion looks really promising. I would also like to test it out as soon as there is something to test.

**Comment by crossworth** [comment]
I have spent some time trying to solve this problem as well (not exactly this problem, but allowing for custom order on entgql, in my case I need to order by a complex result, so it's not only by edge, but multiple edges).

I started with the idea of creating a custom entgql `orderBy` annotation, that accepts a name and a `func(*sql.Selector) string`, something like:

```go
func (Todo) Annotations() []schema.Annotation {
	return []schema.Annotation{
		entgql.OrderByMapping(map[string]func(*sql.Selector) string{
			"CATEGORY_TEXT": func(selector *sql.Selector) string {
				ctbl := sql.Table(category.Table)
				selector.Join(ctbl).On(selector.C(todo.FieldCategoryID), ctbl.C(category.FieldID))
				return ctbl.C(category.FieldText)
			},
		}),
	}
}
```

We would have to change the way `<TYPE>OrderField` works using a `order func(*sql.Selector) string` instead of a string field.
This seems a good fit, since on the `applyOrder` we could call the `direction.orderFunc` to allow both directions (for the fields using `entgql.OrderField` we would create a default order or a helper `orderByField` method).
```go
query = query.Order(direction.orderFunc(p.order.Field.field))
```

But after reading @a8m comment and thinking about a little bit more, I think we should make it available on ent side of things first and allow for more complex queries.

Maybe something like this would work:

```go
func (Todo) OrderBy() []schema.OrderBy {
	return []schema.OrderBy{
		orderby.Name("postsCount").Selector(func(selector *sql.Selector) {
			// not very elegant, since we are changing more than the order for this case
			// but I'm not sure how order by count on another table without doing a join
			ptbl := sql.Table(post.Table)
			subQuery := sql.Select("COUNT(*) AS c", ptbl.C(post.FieldUserID)).
				From(ptbl).
				GroupBy(ptbl.C(post.FieldUserID)).
				As("ord")

			selector.Join(subQuery).On(selector.C(user.FieldID), subQuery.C(post.FieldUserID))
			selector.OrderBy(sql.Desc(subQuery.C("c")))
		}),
	}
}
```

But there are a few problem's with this implementation:
- We have to generate the schema without the orderBy first (to be able to use the predicates and a circular dependency will happen eventually or maybe already exists), this happens to hooks/privacy as well, so there is precedence.
- We are hard coding the direction, maybe the function should accept a direction as argument and use it instead.


There are a few good things as well:
- We could provide custom/common helpers for cases like count of edge `orderby.Name("postsCount").CountByEdge("edgeName")`
- Maybe in the future, allow for defining custom predicates in a similar way


Prev. comments and ref:
- https://discord.com/channels/885059418646003782/885059419107360779/972925468875571370
- https://discord.com/channels/885059418646003782/885059419107360779/1012935142261657681
- https://github.com/crossworth/order-by-count-another-table/blob/659e81f14c977691b3815e6a59d9603ccfd5774b/bug_test.go#L82

**Comment by syssam** [comment]
@crossworth 
If we do not use Relay Cursor Connections Pagination, we can follow the document https://entgo.io/docs/paging#custom-ordering.
However, we do not have any solution with cursor connection pagination.

**Comment by syssam** [comment]
@crossworth @a8m 
can we add a custom order by like https://entgo.io/docs/tutorial-todo-gql-filter-input#custom-filters

**Comment by syssam** [comment]
@a8m any good news on this issue?

**Comment by a8m** [comment]
Hey! The issue was resolved. Check out [the announcement](https://twitter.com/entgo_io/status/1648035851085946880?s=20).
You can upgrade `ent/contrib` to v0.4.1 and check out the docs for examples: https://entgo.io/docs/tutorial-todo-gql-paginate#order-by-edge-count.

Thanks for proposing this, @frederikhors 🙏

**Comment by a8m** [comment]
Hey, @syssam 
To sort by an edge-field, the association must be unique. Otherwise, it won't be possible to order users by the creation time of their posts as a user can have more than one post. For non-unique edges, you can order by aggregation (count, sum, etc) or custom predicates. However, custom predicates need to be manually implemented (until we'll open-source this part).

**Comment by syssam** [comment]
@a8m could you provide a custom predicates code for me? thanks
