### ISSUE TITLE
How to generate updated_at default values like 0000-00-00 00:00:00

### ISSUE THREAD

**Issue by wonderfate** [ent/ent#2834]
How to generate `updated_at` default values like `0000-00-00 00:00:00`

Please help me !!!

```go
field.Time("updated_at").
	SchemaType(map[string]string{
		dialect.MySQL: "datetime",
	}).
	Annotations(&entsql.Annotation{
		Default: "0 ON UPDATE CURRENT_TIMESTAMP",
	}).
	Immutable(),
```
ent: v0.11.1
#### Expected:
  `updated_at DATETIME NOT NULL DEFAULT 0 ON UPDATE CURRENT_TIMESTAMP`

**Comment by henrywoody** [comment]
You can use the `UpdateDefault` method on the field ([docs](https://entgo.io/docs/schema-fields#default-values)) if you just want this type of functionality generally.

Not sure how to do this if you want this functionality at the database level (so that it works from direct database manipulation), but that doesn't really seem like ent's job. In that case you may just have to modify the database migration a bit.

**Comment by wonderfate** [comment]
> You can use the `UpdateDefault` method on the field ([docs](https://entgo.io/docs/schema-fields#default-values)) if you just want this type of functionality generally.
> 
> Not sure how to do this if you want this functionality at the database level (so that it works from direct database manipulation), but that doesn't really seem like ent's job. In that case you may just have to modify the database migration a bit.

I guess this should have customization

**Comment by henrywoody** [comment]
@wonderfate what do you mean by customization?

**Comment by wonderfate** [comment]
@henrywoody  Thank you for your answer.  

Below for the code, that generated query like `deleted_at datetime NOT NULL`
```go
func (DeleteTimeMixin) Fields() []ent.Field {
	return []ent.Field{
		field.Time("deleted_at").
			SchemaType(map[string]string{
				dialect.MySQL: "datetime",
			}),
	}
}
```

But I want to generate it like: `deleted_at DATETIME NOT NULL DEFAULT "0000-00-00 00:00:00" `
Or
 `updated_at DATETIME NOT NULL DEFAULT "0000-00-00 00:00:00" ON UPDATE CURRENT_TIMESTAMP `

I don't know how to define it in `ent`

If you know please teach me!

**Comment by a8m** [comment]
> But I want to generate it like: deleted_at DATETIME NOT NULL DEFAULT "0000-00-00 00:00:00"

The following example should work, and I just verified it locally. 

```go
field.Time("deleted_at").
	SchemaType(map[string]string{
		dialect.MySQL: "datetime",
	}).
	Annotations(entsql.Annotation{
		Default: "1000-01-01 00:00:00",
	})

// Generates: `deleted_at` datetime NOT NULL DEFAULT "1000-01-01 00:00:00"
````

The reason I didn't use all zeros in the `DEFAULT` value, is because MySQL 8 enables the [`NO_ZERO_DATE`](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-setting) mode by default, and `DATETIME` values range is between '1000-01-01 00:00:00' to '9999-12-31 23:59:59'. 

> MySQL does not accept TIMESTAMP values that include a zero in the day or month column or values that are not a valid date. The sole exception to this rule is the special “zero” value '0000-00-00 00:00:00', if the SQL mode permits this value. The precise behavior depends on which if any of strict SQL mode and the [NO_ZERO_DATE](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date) SQL mode are enabled; see [Section 5.1.11, “Server SQL Modes”](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html).

I think this should solve your issue. Please, let me know if we can close this.

**Comment by wonderfate** [comment]
@a8m  Thank you for answer. This's very useful for me.

But when using `Annotations`  there will be duplicate migration files.

 Look at it if you have free time https://github.com/ent/ent/issues/2842

**Comment by a8m** [comment]
Will give it a look of course. Thanks for reporting this.

I think we can close this one and move the discussion to #2842.
