### ISSUE TITLE
[HELP] Trying to implement soft delete logic using Hooks and Mixins

### ISSUE THREAD

**Issue by mirusky** [ent/ent#2850]
I'm trying to implement a soft delete operation, using `Hooks` and `Mixins`, as documentation sugests:

> A Mixin allows you to create reusable pieces of ent.Schema code that can be injected into other schemas using composition.
> The Hooks option allows adding custom logic before and after operations that mutate the graph.

Then I've created the following Mixin, with a Hook in Delete operations:

``` go
type DeletedAt struct {
	mixin.Schema
}

// Fields for all schemas that embed TenantMixin.
func (DeletedAt) Fields() []ent.Field {
	return []ent.Field{
		field.Time("deleted_at").Optional(),
	}
}

func (DeletedAt) Hooks() []ent.Hook {
	return []ent.Hook{
		hook.On(
			func(next ent.Mutator) ent.Mutator {
				type DeletedAtSetter interface {
					SetDeletedAt(time.Time)
				}

				return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
					if ns, ok := m.(DeletedAtSetter); ok {
						ns.SetDeletedAt(time.Now())
					}

					return next.Mutate(ctx, m)
				})
			}, ent.OpDeleteOne|ent.OpDelete,
		),
	}

```

But for some reason it always delete the entity instead of setting deletedAt column, I use it as follow:

``` go
// schame/user.go
func (User) Mixin() []ent.Mixin {
	return []ent.Mixin{
		CreatedAt{},
		UpdatedAt{},
		DeletedAt{},
	}
}

// main.go
func main() {
   // setup and other stuff ...

    client.User.DeleteOne(user).Exec(ctx)
}
```

What I'm missing ?

**Comment by crossworth** [comment]
Hello, the way hooks works is like middlewares, you can hook into a flow of operation and change it. In your case, you are not changing the flow, you return `next.Mutate(ctx, m)`, so you are setting the field and right after that you execute the mutation (that deletes the record).

What you want to do is change the operation, but thats not that easy because the entity type can be anything, I don't think go has a concept of type lookup by name, so we have limited options, you could define this code on each entity definition (not using mixin) and then you could ensure that you know the type and change as you like, but in a generic way is kinda hard.

One simple solution would be to execute raw SQL commands to update the field, that would work, but you need to know the IDs and table name.

A better solution would be to use templates, I created a example for you:
https://github.com/crossworth/ent-soft-delete-hook

Keys points:
https://github.com/crossworth/ent-soft-delete-hook/blob/master/ent/generate.go
https://github.com/crossworth/ent-soft-delete-hook/tree/master/ent/schema
https://github.com/crossworth/ent-soft-delete-hook/blob/ec9836b722ea37032f5312067b5bcffd08d564e4/bug_test.go#L62

In this example we do a type assertion on a few methods that we need (the IDs and the Client), since we got the client from the mutation, this should handle cases like transactions just fine.
We use `IDs` vs `ID` to work with `DeleteOne` and `Delete`.

Inside the function we call a custom template made function, that is responsible for updating the field.

We must return what the mutation excepts, in this case the number of records affected.
![image](https://user-images.githubusercontent.com/1251151/184517188-806aadcf-d26b-4fd6-a762-9402500aa44d.png)

Since we can not do some kind of type resolution during runtime based on a string, we do a switch based on the typ string.
![image](https://user-images.githubusercontent.com/1251151/184517220-d0321eb9-0047-401c-9547-4cefd9b4d19b.png)

But now the question is, how do we do a real delete operation?
To make this work I have created a custom helper function that change the context and our hook wil check it during runtime:
![image](https://user-images.githubusercontent.com/1251151/184517278-a5d1dc6b-3050-43b5-b4a8-6872469e8fec.png)

![image](https://user-images.githubusercontent.com/1251151/184517287-5fb4d92b-536e-4f58-94b9-50ec040497a2.png)


This should work as expected. I commented the test file with the resulting SQL code:
![image](https://user-images.githubusercontent.com/1251151/184517257-12bc8bf7-49b0-49ec-bd78-7401e1bc83dd.png)

I don't know if is the best solution, but it seems to work.

-------
With all that said, you should avoid using soft delete if possible, soft delete [make things hard](https://www.jmix.io/blog/to-delete-or-to-soft-delete-that-is-the-question/), now all your queries will need a predicate to check if the record is not deleted or you may leak information. Direct database access can cause complications as well (everyone will need to ignore the deleted records or at least check it). [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation), [CCPA](https://en.wikipedia.org/wiki/California_Consumer_Privacy_Act) and [LGPD](https://en.wikipedia.org/wiki/General_Personal_Data_Protection_Law) could be hard to comply.

If you really need the data, even if its deleted, you could do things different, like a audit hook, that store the differences from one state to another (I do this on my projects, this way you get the history as well) or if you really need to have the "real" record, create a duplicated table that store the deleted records, on delete operation just copy the record to the `deleted records table`, you will have a clear separation, leaks will be hard to happen and overall your application will get simpler.

I hope this help in any way.

**Comment by mirusky** [comment]
@crossworth thx for your explanation you give me a new view about hooks. I'll try to do it in a different way. I prefer to not use templates since juniors will not completely understand what is happening.

Just 2 questions:

- About the IDs function, you are using `([]int, error)` return but if I've different types of IDs it will break right?

- We could be able to get client from mutation that asserts to a `<project>/ent`.Client, the mutation client is already assigned to current mutating table or I really need to use client.Table.Operation?

I know about security risks involved when doing soft delete, however the way the system is designed here it just stores an ID reference from SSO server. So in that way we don't need to delete all the stuff since it's do not store an user personal data. Also if we delete we could break an background process that creates reports and prepare data for ML team.

**Comment by crossworth** [comment]
> I prefer to not use templates since juniors will not completely understand what is happening.
Funny thing, I used to think this way as well, but there so much GO can do right now (without using reflection/any) and templates do fill the gap, but it's your call, I'm here to help.

> About the IDs function, you are using ([]int, error) return but if I've different types of IDs it will break right?
Yes, it will, what you receive in the mutation is a `ent.Mutation` but the concrete type is `*ent.<Entity>Mutation`, so if you have different types of ID's this could not work. You could in theory do function (with a __template__) that get the correct type of ID and returns the IDs of all types as string (the most compatible I guess) and use raw SQL, but yet I'm not sure, if I'm not mistaken uuid on Postgres requires a casting when setting from a string, so things could get complicated.

You could do more than one type assertion and check for other types of ID's on you application or you could wrap you ID's inside a custom type and use a custom ID with this custom type.

> We could be able to get client from mutation that asserts to a <project>/ent.Client, the mutation client is already assigned to current mutating table or I really need to use client.Table.Operation?
Yeah, this is not the most elegant part, if you start with a empty project, you will not have a `ent.Client` and the hook will not even compile. One way to avoid this is by putting the Client on context and getting using the context, this will work, but now you have to remember to put the client on context always.

About the question, if you check the `*ent.UserMutation` you will see that is very basic, you have options to get/set/clear/remove fields, the only struct you can return I think is the Client. This client is not a special one, I mean, it could be a transactional client, but besides that, it's a simple client.

You may think that you receives the `*<Type>Delete` (a delete builder??) or `*<Type>DeleteOne`, but that's not what you get and even if you got one of those, you could not convert then to a `*<Type>Update` or `*<Type>UpdateOne`.

I explored a little bit changing the Op, but that will not work, since the next mutation is the one that deletes and it dont really care about the Op.

Things you could explore without using templates:
- Using reflection: it will be slower and it will be hard to understand.
- Maybe you could do a trigger trick, create a trigger that do the update and return an [error on delete](https://stackoverflow.com/a/29902060) (abort the delete operation), capture the error on the hook and treat as success, I'm not sure if this actually works and even if works, I wonder how you would do a real delete.
- Softdelete on driver level, you would need a parse for the generated SQL code, but I think is possible, parse the SQL on Exec and Tx Exec, check the type and change for update.
- In theory if you could create a `UpdateMutation` somehow it would work, but I don't see a way to do it without using `ent.Client`.

 Maybe you could find a better way, if you do, please share with us.

**Comment by CyrivlClth** [comment]
I also try to implement soft delete when using entgo. But after thinking about it carefully, I think it is only necessary to add query conditions in query hooks, and then use update in service to replace the original delete method.

**Comment by a8m** [comment]
Hey all! Interceptors were added to Ent, and you can implement something like soft-delete with a shared Mixin in your project. Please, check out https://entgo.io/docs/interceptors#soft-delete and feel free to join our [Discord](https://discord.gg/qZmPgTE6RX) and ping me if you have any troubles with it.

**Comment by weijinnx** [comment]
What if I want to get ONLY soft deleted records? Didn't find any docs to do that, in docs we can retrieve all records (with soft deleted), or just active records. But I need also to find ONLY SOFT DELETED records. Thanks!
