### ISSUE TITLE
Export transaction context

### ISSUE THREAD

**Issue by Antonboom** [ent/ent#2864]
Hello!

```go
// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
    // ...

    // ctx lives for the life of the transaction. It is
    // the same context used by the underlying connection.
    ctx context.Context
}
```

It will be useful for functions like
```go
func Put(tx ent.Tx, name, payload string) (JobID, error)
```

**Comment by a8m** [comment]
Hey @Antonboom and thanks for proposing this option 🙏 

The only reason the `context.Context` is stored on the Ent's transactions, is because we want to pass it to the [Transaction Hooks](https://entgo.io/docs/transactions/#hooks), but `Commit` and `Rollback` don't accept it as argument (in `sql.Tx`).

I prefer to not expose it as a struct member because that's not the recommended way in Go to pass context:

> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it.

See [context documentation](https://pkg.go.dev/context) for reference. BTW, `http.Request.Context` is exceptional, because there was no way to add it to `http.Handler` without changing/extending the interface. 

Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) if you have more questions or want to discuss this in more detail 😃.

**Comment by Antonboom** [comment]
@a8m, I know Go recommendations.

But there are many examples where the context is replaced with a custom context containing it.
And your transaction is one of this?

```go
func Put(ctx context.Context, tx *ent.Tx, name, payload string, availableAt time.Time) (types.JobID, error) {
    j, err := tx.Job.Create().
        // ...
        Save(ctx)
    // ...
}
```

vs

```go
func Put(tx *ent.Tx, name, payload string, availableAt time.Time) (types.JobID, error) {
    j, err := tx.Job.Create().
        // ...
        Save(tx.Ctx())
    // ...
}
```

Now I have to make my own wrapper over your transaction.
What do you think?

**Comment by a8m** [comment]
The `context.Context` is usually the first argument to a function,  so the second example is excellent.

Also, using the transaction context may not be good for some cases, because the hierarchy there is like a tree, and a function like `Put` should use the right context in the hierarchy (e.g. telemetry, authz, etc) and not the one used for opening the transaction; In entgql for example, there's a middleware that opens a transaction when a mutation request hits the server. The context may "extended" somewhere later in the request handling, and using the one used to open the transaction is not right.
