### ISSUE TITLE
`.Limit(0)` in query should be omitted

### ISSUE THREAD

**Issue by waltcow** [ent/ent#2907]
`Limit` limits the query result to `n` entities. but when it comes to `0`
 It will be meaningless and should be omitted in sql 
```go
users, err := client.User.Query().Unique(false).Limit(limit).Offset(10).All(ctx)
```

sql  generated as followed

```
 driver.Query: query=SELECT "********" FROM "users" LIMIT 2147483647 OFFSET 10
```

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Steps to Reproduce 🕹

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.17.?  |
| Ent         | 0.9.?   |
| Database    | MySQL   |
| Driver      | https://github.com/go-sql-driver/mysql        |

**Comment by a8m** [comment]
Hey @waltcow and thanks for reporting this. 

I'm not able to reproduce this using your example because the logic there is different. As you can see, the [logic in sqlgraph](https://github.com/ent/ent/blob/master/dialect/sql/sqlgraph/graph.go#L632-L636) appends a default `LIMIT` (math.MaxInt32) only if the `OFFSET` was provided and `LIMIT` was **0 or was not set**. This is needed because the `OFFSET` cannot be used without `LIMIT` in some databases. See SQLite as an example:

<img src="https://user-images.githubusercontent.com/7413593/188807158-f067ca61-6b0b-4056-8a68-33f9ab8f05a5.png" width="50%"/>

**Comment by a8m** [comment]
Please, let me know if I can close this issue. I'm also available in our [Discord community](https://discord.gg/qZmPgTE6RX) for any questions.

**Comment by waltcow** [comment]
@a8m example above is missing `.Offset()` clause , I have updated in comment

**Comment by a8m** [comment]
We can omit this default `LIMIT` in PostgreSQL. Please, feel free to contribute this patch. Thanks 🙏

**Comment by waltcow** [comment]
> Hey @waltcow and thanks for reporting this.
> 
> I'm not able to reproduce this using your example because the logic there is different. As you can see, the [logic in sqlgraph](https://github.com/ent/ent/blob/master/dialect/sql/sqlgraph/graph.go#L632-L636) appends a default `LIMIT` (math.MaxInt32) only if the `OFFSET` was provided and `LIMIT` was **0 or was not set**. This is needed because the `OFFSET` cannot be used without `LIMIT` in some databases. See SQLite as an example:
> 
> <img alt="" width="50%" src="https://user-images.githubusercontent.com/7413593/188807158-f067ca61-6b0b-4056-8a68-33f9ab8f05a5.png">

Thanks for showing me the related `sqlgraph`, ` Limit` is needed obviously.
