### ISSUE TITLE
how to do?example:"'UPDATE ' . table . ' SET stock=stock+?,locked_stock=locked_stock-? WHERE sku_id=? AND stock<=total_stock-? AND locked_stock>=?';"

### ISSUE THREAD

**Issue by pangweiqiang** [ent/ent#2932]
How to write ent in this way
stock<=total_stock-?

**Comment by a8m** [comment]
Hey @pangweiqiang and thanks for raising this issue 👋 

The following can be written as follows:

```go
client.T.Update().
    AddStock(v1).
    AddLockedStock(-v2).
    Where(
        t.SkuID(v3),
        t.LockedStockGTE(v4),
        // A custom predicate for the second condition.
        func(s *sql.Selector) {
            s.Where(sql.LTE("stock", Expr("total_stock - ?", v5)))
        },
    ).
    Exec(ctx)
```

Another approach (which is preferred IMO), is instead of using raw strings to use the generated columns:
```go
s.Where(sql.LTE(t.FieldStock, sql.P(func(b *Builder) {
    b.Ident(t.FieldTotalStock).WriteOp(OpSub).Arg(v5)
})))
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this 😃

**Comment by pangweiqiang** [comment]
cool !
think you very much!
