### ISSUE TITLE
Why entgql raises error on empty where input predicates? Isn't it better to just ignore them?

### ISSUE THREAD

**Issue by vincentluan** [ent/ent#2948]

**Comment by a8m** [comment]
Hey @vincentluan 👋🏻
A call to `P()` will return an error in case the predicate is empty, because you can’t use it as an input in the `Where` clause. 

However, you can ignore it same as we do it in the `Filter` option. See: https://github.com/ent/contrib/blob/master/entgql/internal/todo/ent/gql_where_input.go#L124

Closing, but please reopen if you still need help with it.

**Comment by vincentluan** [comment]
Thanks Ariel. Is this going to be released anytime soon?

**Comment by a8m** [comment]
I’m pretty sure the latest git tag contains these changes. Please upgrade your ent/contrib version and let me know if there is any issue with it.

**Comment by vincentluan** [comment]
Oh my bad. Thanks a lot Ariel.
