### ISSUE TITLE
Migration: Column "x" can not be cast automatically to type T (SQLSTATE N)

### ISSUE THREAD

**Issue by TheBeachMaster** [ent/ent#3002]
I had a field `h_count` that was **(by mistake)** set to type `String`, I have updated it to the correct type `Int` 

```diff
- field.String("h_count"),
+ field.Int("h_count"),
```

Attempting to migrate as [documented here](https://entgo.io/docs/migrate/#drop-resources), results into the error below

```go
//... A lot of stuff

if err := client.Schema.Create(context.Background(), schema.WithAtlas(true), migrate.WithDropIndex(true), migrate.WithDropColumn(true)); err != nil {
  log.Fatalf("%v", err)
}
```

```sh
sql/schema: modify "a_transactions" table: ERROR: column "h_count" cannot be cast automatically to type bigint (SQLSTATE 42804)
```

Ent version:  `entgo.io/ent v0.11.4-0.20221001062602-1029a2d3ba2a`
DB: Postgres

How does one resolve such?

**Comment by a8m** [comment]
Hey @TheBeachMaster, and thanks for raising this issue. 
Atlas (used by Ent) does not append type casting (i.e. [`USING`](https://www.postgresql.org/docs/current/sql-altertable.html)) to the statement because it cannot assume what the desired way to handle such conversions. 

I guess the table is empty in your case because the first `field.String` was added accidentally. My suggestion then, in this case, is to drop the column and add it again, or append type-conversion with [apply-hooks](https://entgo.io/docs/migrate/#atlas-diff-and-apply-hooks) like the one below if you're sure the strings in this column represent integers:

```sql
ALTER TABLE "a_transactions" ALTER COLUMN "h_count" bigint USING "h_count"::bigint
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) if you still need help with this.
