### ISSUE TITLE
Postgres Fulltext search Modify function 

### ISSUE THREAD

**Issue by martingrzzler** [ent/ent#3042]
I'm trying to make a fulltext search query and order the result by `ts_rank_cd`. `sql.P` is very useful for the `WHERE` clause but I'm struggling with `ORDER BY`. The code below works but I had to look at the raw query to know that I have to use `$4` in order to make it work. This may be a general limitation of `sql.Expr` but is there a better way of doing it? To be more specific can I write a `ORDER BY` clause based on `ts_rank` without worrying about the correct argument number?

```go
err = team.QueryUsers().
Modify(func(s *sql.Selector) {
	s.
		Where(sql.P(func(b *sql.Builder) {
			b.Ident("document").
				WriteString(" @@ websearch_to_tsquery(").
				Arg(input.Search).
				WriteByte(')')
		})).
		OrderExpr(sql.ExprP("ts_rank_cd(document, websearch_to_tsquery($4))", input.Search))
}).
Scan(ctx, &users)

```

**Comment by a8m** [comment]
Hey @martingrzzler 👋 
For custom modifiers/builders, I recommend you use an `sql.ExprFunc` and not `Expr` (with `?`) if you're using PostgreSQL. That's because PostgreSQL is using positional arguments instead of the MySQL/SQLite placeholder syntax (?). 

Please, see [this example](https://github.com/ent/ent/blob/master/dialect/sql/builder_test.go#L1673-L1678) (`Arg` calls), and let me know if you need more help. You are also welcome to join our [Discord community](https://discord.gg/zZ6sWVg6NT) and tag me there 😎

**Comment by martingrzzler** [comment]
Awesome! Thank you.

For anyone interested:
```go
OrderExpr(sql.ExprFunc(func(b *sql.Builder) {
	b.WriteString("ts_rank_cd(").
		Ident("document").
		Comma().
		WriteString("websearch_to_tsquery(").
		Arg(input.Filter.Search).
		WriteString("))")
}))

```
