### ISSUE TITLE
[Question] How can I use like  mysql 'JSON_SEARCH' func in  ent?

### ISSUE THREAD

**Issue by yrzs** [ent/ent#3083]
I didn't  see any json field's func generated in where.go

**Comment by a8m** [comment]
Hey @yrzs 👋 
There are a few examples in the docs and our integration tests for working with JSON predicates. See:
https://entgo.io/docs/predicates#json-predicates
https://github.com/ent/ent/blob/master/entc/integration/json/json_test.go#L328

Note that `JSON_SEARCH` is not there, because it was not added to the `sqljson` package. However, you can implement it for your app and use it as a custom predicate. The examples in this file may help you:
https://github.com/ent/ent/blob/master/dialect/sql/sqljson/sqljson.go

**Comment by yrzs** [comment]
> Hey @yrzs 👋 There are a few examples in the docs and our integration tests for working with JSON predicates. See: https://entgo.io/docs/predicates#json-predicates https://github.com/ent/ent/blob/master/entc/integration/json/json_test.go#L328
> 
> Note that `JSON_SEARCH` is not there, because it was not added to the `sqljson` package. However, you can implement it for your app and use it as a custom predicate. The examples in this file may help you: https://github.com/ent/ent/blob/master/dialect/sql/sqljson/sqljson.go

@a8m think you! I found it.
