### ISSUE TITLE
How to access predicates in a hook?

### ISSUE THREAD

**Issue by hbagdi** [ent/ent#3356]
I'm using ent 0.11.4 and I'm implementing a change feed for all successful INSERT/UPDATE/DELETEs.
The thing is that the DELETE statement is being performed using a WHERE clause which means that the mutation.ID() returns nil.
I'm trying to figure out how can I grab the ID from the predicate instead.

**Comment by a8m** [comment]
Hey @hbagdi 👋 
For `UpdateOne` and `DeleteOne`, the ID is available in the mutation, and you can get it by calling `Mutation.ID()`. See an example: https://github.com/ent/ent/blob/master/entc/integration/hooks/hooks_test.go#L201-L204

However, for `Update` and `Delete` operations, the `ID` is not exposed, even though it's stored in the predicate closure. The reason is that on these two operations, multiple nodes can be affected, so it's recommended to call the `Mutation.IDs` methods to get all affected nodes. See this example: https://github.com/ent/ent/blob/master/entc/integration/hooks/hooks_test.go#L129-L133



Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
