### ISSUE TITLE
【Quenstion】How can i use O2M Edge with a json field?

### ISSUE THREAD

**Issue by yrzs** [ent/ent#3384]
// Fields of the CopyrightIp.
func (CopyrightIp) Fields() []ent.Field {
	return []ent.Field{
		field.Uint32("id").SchemaType(map[string]string{
			dialect.MySQL: "int(10)unsigned", // Override MySQL.
		}).Comment("主键ID").Unique(),
	}
}

// Fields of the CopyrightList.
func (CopyrightIPList) Fields() []ent.Field {
	return []ent.Field{
		field.Uint32("id").SchemaType(map[string]string{
			dialect.MySQL: "int(10)unsigned", // Override MySQL.
		}).Comment("主键ID").Unique(),
		field.JSON("ip_ids",[]uint32{}).SchemaType(map[string]string{
			dialect.MySQL: "json", // Override MySQL.
		}).Comment("版权IP"),
	}
}

**Comment by a8m** [comment]
Hey @yrzs,
You can't define edges (foreign keys in this case) as a JSON array because a foreign-key constraint is necessary for each relation. What you can do instead is define an O2M relation like this example: https://entgo.io/docs/schema-edges#o2m-two-types:

```go
func (CopyrightIPList) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("ips", CopyrightIP.Type),
    }
}

// The inverse definition is optional.
func (CopyrightIP) Edges() []ent.Edge {
    return []ent.Edge{
        edge.From("list", CopyrightIPList.Type).
            Ref("ips").
            Unique(),
    }
}
```

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
