### ISSUE TITLE
ent/new: could not parse template template: data.tmpl:39: function "Line" not defined

### ISSUE THREAD

**Issue by oaktreecode** [ent/ent#3475]
> go 1.20

require (
	entgo.io/contrib v0.4.0
	entgo.io/ent v0.12.0
	github.com/99designs/gqlgen v0.17.28
	github.com/casbin/casbin/v2 v2.66.3
	github.com/gin-gonic/gin v1.9.0
	github.com/go-kratos/gin v0.1.0
	github.com/go-kratos/kratos/v2 v2.4.1
	github.com/go-sql-driver/mysql v1.7.0
	github.com/google/uuid v1.3.0
	github.com/google/wire v0.5.0
	github.com/hashicorp/go-multierror v1.1.1
	github.com/pkg/errors v0.9.1
	github.com/vektah/gqlparser/v2 v2.5.1
	go.uber.org/automaxprocs v1.5.1
	go.uber.org/zap v1.24.0
	golang.org/x/crypto v0.8.0
	google.golang.org/genproto v0.0.0-20221118155620-16455021b5e6
	google.golang.org/grpc v1.52.3
	google.golang.org/protobuf v1.28.1
)

> tmpl content:

```
if err != nil {
 		return nil, &gqlerror.Error{
 			Message: "An unexpected error occurred while trying to create the {{ . }}",
 			Path:    graphql.GetPath(ctx),
 			Locations: []gqlerror.Location{{
 				Line: 31,
 			}},
 			Extensions: map[string]interface{}{
 				"code": "DATA_CREATE_{{ . }}_FAILED",
 				"err":  err.Error(),
 			},
 			Rule: "Create{{ . }}",
 		}
```

> Got the error:
ent new SysOperationLog --target=./internal/data --template=./internal/data/ent/template/data.tmpl
ent/new: could not parse template template: data.tmpl:39: function "Line" not defined

**Comment by a8m** [comment]
Hey @oaktreecode 👋 
It looks like this error comes from this external template (ent does not have a template named "data"). If you want to fix this, you need to add an extra space between the curly braces so that the template parser won't interpret it as an action e.g.,

```diff
-Locations: []gqlerror.Location{{
+Locations: []gqlerror.Location{ {
	Line: 31,
-}},
+} },
```

Closing, but you're more than welcome to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😃

**Comment by oaktreecode** [comment]
GOT IT, MANY THANKS @a8m
