### ISSUE TITLE
Entity `Exec` should not call SELECT under the hood

### ISSUE THREAD

**Issue by iagomelanias** [ent/ent#3499]
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Related #889

I know the issue above is closed, but I've just faced the same problem. It's kinda confusing because `Exec` doesn't return the entity, so I thought no `SELECT` would be called under the hood, which proved to be wrong when I decided to take a look at the logs by enabling the debug mode.

Is there any way to disable this additional query?

If not, changing the way it works currently is a breaking change? I would like to contribute to this change if it makes sense.

## Motivation 🔦

It impacts the performance in a way that most people won't notice during the development.

**Comment by a8m** [comment]
Hey, @iagomelanias 👋 

> Is there any way to disable this additional query?

See my comment at https://github.com/ent/ent/issues/889#issuecomment-717770387. You can use the `Update` builder instead of the `UpdateOne` as follows:

```go
err := client.User.
    Update().
    Where(user.ID(id)).
    SetName(...).
    Exec(ctx)
```

> If not, changing the way it works currently is a breaking change? I would like to contribute to this change if it makes sense.

It's (currently) not possible because [hooks](https://entgo.io/docs/hooks/) and [privacy rules](https://entgo.io/docs/privacy) rely on this. i.e., when `Mutation.Op` is `ent.OpUpdateOne` the returned `ent.Value` should be the updated node. Regardless of whether you call `Exec` or `Save`. See https://github.com/ent/ent/pull/2112#issue-1046504928 for more info.

Closing this, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) if you'd like to continue discussing this 😎

**Comment by iagomelanias** [comment]
Hey @a8m,
Thanks for the info. I'm aware it's possible to "avoid" this additional query by using `Update` directly (_I read the mentioned comment during my research_), but it comes at a cost of additing complexity to the development and potentially adding bugs, since both `Get` and `Update` must match the same query conditions. I'm joining the Discord community so we can discuss if the `Exec` behavior could or should be changed.
