### ISSUE TITLE
running demo with error： failed creating schema resources: sql/schema: reversd alter table "users": column "age" of type *schema.IntegerType does not support the CHARSET attribute

### ISSUE THREAD

**Issue by alv00** [ent/ent#3501]
I have tried running the demo offered in quick introduction ：https://entgo.io/zh/docs/getting-started
When the "user" table not exists, I executed `go run start.go` succeed.
When the "user" table exists,I executed `go run start.go` failed.Error occurred: failed creating schema resources: sql/schema: reversd alter table "users": column "age" of type *schema.IntegerType does not support the CHARSET attribute.
DB: Oceanbase-CE 4.1.0.0, it is compatible with mysql dialect

connInfo := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?timeout=10s&charset=utf8&parseTime=True&loc=Local&interpolateParams=true", user, pwd, ip, port, dbName)
client, err := ent.Open("mysql", connInfo)

show create  table test.users:
CREATE TABLE `users` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `age` bigint(20) NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT 'unknown',
  PRIMARY KEY (`id`)
) AUTO_INCREMENT = 1 AUTO_INCREMENT_MODE = 'ORDER' DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 3 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0

**Comment by alv00** [comment]
connInfo := fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?timeout=10s&charset=utf8&parseTime=True&loc=Local&interpolateParams=true", user, pwd, ip, port, dbName)
client, err := ent.Open("mysql", connInfo)

**Comment by a8m** [comment]
Hey, @alv00 👋 

> DB: Oceanbase-CE 4.1.0.0, it is compatible with mysql dialect

I never tested Oceabase, but it looks like the information_schema is not compatible with MySQL/MariaDB. Can you try running the following query?

```sql
SELECT `TABLE_NAME`, `COLUMN_NAME`, `COLUMN_TYPE`, `COLUMN_COMMENT`, `IS_NULLABLE`, `COLUMN_KEY`, `COLUMN_DEFAULT`, `EXTRA`, `CHARACTER_SET_NAME`, `COLLATION_NAME`, NULL AS `GENERATION_EXPRESSION` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = 'test' AND `TABLE_NAME` = 'users' ORDER BY `ORDINAL_POSITION`;
```

**Comment by alv00** [comment]
![image](https://user-images.githubusercontent.com/106736449/233968511-80fe7104-d527-452b-a11d-0fe2872ff938.png)

**Comment by a8m** [comment]
Thanks for testing it, @alv00. In MySQL and MariaDB, The `CHARACTER_SET_NAME` column exists for string types and should be NULL for both `id` and `age` in your use case above. 

![image](https://user-images.githubusercontent.com/7413593/233969905-f4d3500d-55ca-4de0-8f3c-cba54054df80.png)
![image](https://user-images.githubusercontent.com/7413593/233970064-3926f612-fa85-4b0b-adc4-f4b743e9cd1c.png)

Since we don't support Oceanbase at the moment, you can workaround this behavior by using [Diff Hooks](https://entgo.io/docs/migrate#atlas-diff-and-apply-hooks) and remove the charset/collation attributes from non-string columns.
