### ISSUE TITLE
Is there a way to make some sort of schema validation?

### ISSUE THREAD

**Issue by Breigner01** [ent/ent#3552]
So basically I have 2 programs accessing the exact same DB.
I have the main one that makes the call to `client.Schema.Create` but the 2nd one doesn't.
I have made an external (private) library with the schema and queries which is being imported in both programs.
I would like to be able to have something like `client.Schema.Validate` which would check whether the schema in the DB to which it is connected matches the one used by ent.
This would allow me to make sure it has the right version of the library.

So is there a way to do that?

If not, is it planned?

**Comment by a8m** [comment]
Hey, @Breigner01 👋 

You can use migration "diff hooks" to hook into the migration process and return an error if there are changes. For example,
```go
err := client.Schema.Create(
	ctx,
	// Hook into Atlas Diff process.
	schema.WithDiffHook(func(next schema.Differ) schema.Differ {
		return schema.DiffFunc(func(current, desired *atlas.Schema) ([]atlas.Change, error) {
			changes, err := next.Diff(current, desired)
			switch changes, err := next.Diff(current, desired); {
			case err != nil:
				return nil, err
			case len(changes) > 0:
				return nil, fmt.Errorf("unexpected changes: %v", changes)
			default:
				return nil, nil
			}
		})
	}),
)
```

That being said, I think a proper solution for this problem is to use versioned migration: https://entgo.io/docs/versioned-migrations

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by Breigner01** [comment]
Hey,
Thanks for the solution.
I see the point of versioned migrations, I just don't think it would allow me to use the same functions on both programs without rewriting them.
This external library contains both the schema and queries.
Anyway, do you plan on making an easier way of checking whether the schemas matches or is it out of scope?
