### ISSUE TITLE
About not mapping field

### ISSUE THREAD

**Issue by nieshaoyu** [ent/ent#3661]
Hey,  I'd like to inquire about fields in the database that are not being mapped.
The schema：
`func (User) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
		field.String("token").
			Optional().
			Nillable().
			Comment("Transient field for storing token data in-memory"),
	}
}`
but the ‘token’ Field not in the table column. When i use Query() method ，its takes Error: Unknown column 'user.token' in 'field list'.
What do I need to add the Transient  Field? thanks

**Comment by a8m** [comment]
Hey @nieshaoyu 👋 

In order to add static fields to your struct that **do not exist in the database**, you can use the custom templates as described here: https://entgo.io/docs/schema-fields#additional-struct-fields. 

Closing, but please feel free to reopen or join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
