### ISSUE TITLE
[FR] entc execute extension only

### ISSUE THREAD

**Issue by letientai299** [ent/ent#3663]
I'm writing a few extensions that contribute external templates for my project, and have to frequently run `entc` to review the output template. That's quite slow since I have lots of tables.

Since the only thing changes between executions is the code generated from my extensions, I think it would be much faster if `entc` can skip generate all the entities code and only execute the extensions.

Do we have any way to do it with current public API yet? If not, please consider this feature request, as that would make the DX nicer.

**Comment by a8m** [comment]
Hey @letientai299 👋 

If I understand correctly, it sounds more like a development problem rather than a feature for Ent. For this case, I suggest you write unit tests on example schemas/types same as we do in [entgql](https://github.com/ent/contrib/tree/master/entgql), [entproto](https://github.com/ent/contrib/tree/master/entproto), or even in [entc/gen](https://github.com/ent/ent/blob/master/entc/gen/graph_test.go) itself (this is a more low-level example). 


Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
