### ISSUE TITLE
Unique() does not lead to expected behaviour on SQL

### ISSUE THREAD

**Issue by roaldvanloon** [ent/ent#3718]
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Given an entity X with a schema containing 3 fields;
- id
- field1
- field2

I would like to know the unique combinations of (field1, field2). However when executing the following;

`X.Query().Unique().Select(field1, field2).All()`

The query always includes the id field, which leads to SQL;

`SELECT DISTINCT "X"."id", "X"."field1", "X"."field2" FROM "table"`

This will not return the unique combinations of (field1, field2).

## Expected Behavior 🤔

I expect the following query to be executed;

`SELECT DISTINCT "X"."field1", "X"."field2" FROM "table"`

## Steps to Reproduce 🕹

Any schema will have this behaviour.
The id field is always added in the generated code, in `func (... XQuery) querySpec() *sqlgraph.QuerySpec {...}`

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.21.0  |
| Ent         | 0.12.3   |
| Database    | postgresql  |

**Comment by a8m** [comment]
Hey, @roaldvanloon 👋 

The `All`/`First`/`Only`/etc options return nodes - nodes (objects) are always different. When nodes are returned, you can update them, query their relations, etc. That's why the ID is necessary when querying nodes.

However, if you want to get unique tuples/columns/aggregations, you can use the `Select`+`Scan` API as explained in this example: https://entgo.io/docs/crud#field-selection. For example:

```go
var vs []struct {
    Field1 string `sql:"field1"`
    Field2 string `sql:"field1"`
}
client.T.Query().Unique(true).Select(..).Scan(ctx, &vs)
```

Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎
