### ISSUE TITLE
error calling gqlIDType: entgql: mixed id types must be type string or implement

### ISSUE THREAD

**Issue by HideNeg** [ent/ent#3725]
Hello,

I am currently developing with Ent and am having trouble with GraphQL generation.

When I run `go generate .`, I get the following message:

```
2023/09/03 16:25:39 running ent codegen: execute template "client": template: node.tmpl:315:16: executing "client/fields/additional" at <gqlIDType (filterNodes $.Nodes (skipMode "type")) $.IDType>: error calling gqlIDType: entgql: mixed id types must be type string or implement the graphql.Marshaller/graphql.Unmarshaller interfaces
```

Does this message imply that the ID in ent/schema must be of type String?

In my ent/schema, the IDs for each schema are either String or Int only.

Has there been a similar issue already?

I would appreciate any insights you can offer.

Thank you for your cooperation.

よろしくお願いします🙇‍♂️

**Comment by a8m** [comment]
Hey @HideNeg 👋 

The issue was answered here: https://github.com/ent/ent/issues/2638. The ID must be a consistent scalar type (e.g., int or string) if you're using the built-in Go types. However, you can implement your custom type and implement the `graphql.Marshaler`/`graphql.Unmarshaler` interfaces as explained in https://github.com/ent/ent/issues/2638.


Closing, but please feel free to join our [Discord community](https://discord.gg/qZmPgTE6RX) in case you need more help with this 😎

**Comment by HideNeg** [comment]
@a8m 
Thank you so much !
