### ISSUE TITLE
why select always append id

### ISSUE THREAD

**Issue by english943** [ent/ent#3871]
i try to generate a sql: `select distinct a, b from t`

the code: `client.T.Query().Unique(true).Select(t.FieldA, t.FieldB).All(ctx)`

ent generate a sql: `select distinct id, a, b from t`

it always append id and i can't select distinct fields without id.
is there any way to generate what i want?

**Comment by a8m** [comment]
Hey @english943 👋 

`All`, `Only` `First`, and similar functions return objects (entities). After an object is returned, you can query its associations/edges, update it, delete it, etc. An ID is necessary for these operations, which is why ent adds it by default. However, you can still execute such queries in ent as explained in this document: https://entgo.io/docs/crud#field-selection.

```go
var v []struct {
    A int `sql:"a"`
    B int `sql:"b"`
}
client.T.Query().Unique(true).Select(t.FieldA, t.FieldB).Scan(ctx, &v)
```
