### ISSUE TITLE
Why goes go generate require packages that are out of scope/should not be referenced?

### ISSUE THREAD

**Issue by JakeTrock** [ent/ent#3963]
I was initializing a project using your software, and ran `go generate ./...`

- [x ] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I am currently getting the following when running the `go generate ./...` command in the root of my project(and also I've tried running it within the ent folder, same result):
```
/Users/kapn/.asdf/installs/golang/1.22.0/packages/pkg/mod/github.com/mailru/easyjson@v0.7.7/jlexer/lexer.go:19:2: missing go.sum entry for module providing package github.com/josharian/intern (imported by github.com/mailru/easyjson/jlexer); to add:
        go get github.com/mailru/easyjson/jlexer@v0.7.7
create.go:12:2: no required module provides package entgo.io/ent/examples/fs/ent; to add it:
        go get entgo.io/ent/examples/fs/ent
2024/03/04 11:24:29 running ent codegen: exit status 1
exit status 1
ent/generate.go:3: running "go": exit status 1
```
This presents two different concerns for me, firstly that it wants me to import a package that's lower in the dependency tree, and then that it wants me to import a package that is an example. These imports are in generated code, so I shouldn't have to change them, but when I tried installing easyjson and truncating `entgo.io/ent/examples/fs/ent` to `entgo.io/ent`, I got several errors. The code that causes this is located [here](https://github.com/studenture/stugo)

this is what one of the automatically generated imports look like(for `/ent/output/http/create.go`):
```
// Code generated by ent, DO NOT EDIT.

package http

import (
	"net/http"
	"studenture/ent/output/auth"
	"studenture/ent/output/post"
	"studenture/ent/output/profile"
	"studenture/ent/output/tag"

	"entgo.io/ent/examples/fs/ent" //bad!
	"github.com/mailru/easyjson" // bad!
	"go.uber.org/zap"
)
```

## Expected Behavior 🤔

I expected the code to be generated without a hitch (this works successfully for me with the pets example) and be able to run the webserver

## Steps to Reproduce 🕹

Steps:

1. clone my [code](https://github.com/studenture/stugo)
2. run `go generate ./...` in the root
3. look at the debug output/generated code
4. cry

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          | 1.22.0  |
| Ent         | 0.13.1   |
| Database    | MySQL   |
| Driver      | https://github.com/mattn/go-sqlite3       |

**Comment by crossworth** [comment]
The `easyjson` is because `elk` needs it  https://github.com/masseelch/elk/blob/179c3329e0141fc528af34f8d19ae8db94073004/template/http/import.tmpl#L10

Run the code to add the required dependency:
```
go get github.com/mailru/easyjson/jlexer@v0.7.7
```

Now the `entgo.io/ent/examples/fs/ent` I'm pretty sure is related how the `goimports` works with a possible hard-coded template (I'm not 100% sure and don't have the time to check for the template right now).

If you change the `Target` and `Package` to end with `/ent` it works.

```go
err = entc.Generate("./schema", &gen.Config{
	Schema:  "./schema",
	Target:  "./ent",
	Package: "studenture/ent/ent",
}, entc.Extensions(ex))
if err != nil {
	log.Fatalf("running ent codegen: %v", err)
}
```

I think a template is hard-coded to use a package `ent` somewhere, since you changed yours to be `output`, during the generate process `goimports` tries to import the missing packages, it finds a `ent` package and uses the `entgo.io/ent/examples/fs/ent` one.

I think the problem is with https://github.com/masseelch/elk/blob/179c3329e0141fc528af34f8d19ae8db94073004/template/http/helpers.tmpl#L83 `ent.IsNotFound` and `ent.IsNotSingular`.

**Comment by giautm** [comment]
Please use entoas instead, https://github.com/masseelch/elk?tab=readme-ov-file#important

**Comment by JakeTrock** [comment]
Thank you so much for the quick and helpful comments, I'll be sure to heed them. I may have to message the people involved w/ elk sometime with a pr to update their wiki so more people don't come down this path trying to do the sample exercise

**Comment by JakeTrock** [comment]
Thank you so much for the quick and helpful comments, I'll be sure to heed them. I may have to message the people involved w/ elk sometime with a pr to update their wiki so more people don't come down this path trying to do the sample exercise
