### ISSUE TITLE
Feature: Multi-Key Primary

### ISSUE THREAD

**Issue by aight8** [ent/ent#400]
Feature: Multi-Key Primary

Are relatively common in certain cases

SQL stores supports this, for the graph db (or when it's not supported), there could be a workaround. Save both fields in one field with a delimiter.
However it's not allowed then to query by only one PK field (because it's stored as one field).

**PRO**

**The advantages of multi-field-PK in aspect as Lib User:**
The business logic should not care about field construction (merge/split/extra-queries) and all those hacks.
PK related functions require simply both (or more) PK field values.
The code is much more business logic-oriented (no confusing find-by-ID which should be avoided etc.)

**The advantages of multi-field-PK in aspect of the Store**
deterministic PK constructed by two args.
no unnecessary default ID PK field

**CONTRA**

Maybe no-sql stores not supports this... workarround could be difficult.

**Current the nicest workaround is:**

Let the default ID field as it is.
Define two fields and a common unique index on it.

**Comment by a8m** [comment]
Hey @aight8 and thanks for proposing this!

I honestly prefer the ID field to be as it is today, because it works nice with other things like the universal-id support and the GraphQL ID field. If we'll add this functionality, other features won't work (for tables that use this) - and I'm fan of this. 

IMO, If someone wants to define a multi-fields uniqueness, he can just use a unique index for this.  

Of course, this is just my opinion and let's see what others think about this.

**Comment by a8m** [comment]
Hey @aight8 and thanks for proposing this!

I honestly prefer the ID field to be as it is today, because it works nice with other things like the universal-id support and the GraphQL ID field. If we'll add this functionality, other features won't work (for tables that use this) - and I'm not fan of this. 

IMO, If someone wants to define a multi-fields uniqueness, he can just use a unique index for this.  

Of course, this is just my opinion and let's see what others think about this.

**Comment by aight8** [comment]
Hi,
no understand your conclusion than, when it does not make sense with a commonly used overlayed technology graphql.

this issue is a little bit more, because you it would change the generated code and how you use the code.

maybe keep in mind that ent have great potential to be a common-purpose DB access layer. it were nice if it were extensible enough at least to allow some DB specific structure optimizations.
-> same for
- computed fields (the immutable option should allow the biggest I think, but don't tested it)
- and column constraint checks (is just db specific)
however should be discussed somewhere else...

**Comment by vojta001** [comment]
Can I kindly ask what the current state of this feature is? And what are the plans? Don't we want to add this to #46?

Or at least, is there any workaround? Defining a unique index over multiple columns is fine, but it doesn't help with the relations/edges, that still use the default `id` column.

**Comment by vojta001** [comment]
To add my opinion: I feel like composite primary keys used for relations are kinda frequent as it provides an additional level of consistency enforcement.

Emulating composite PK by putting multiple values into a single column does not seem important to me. It is a workaround for people who want a feature their DB does not provide, isn't it?

**Comment by a8m** [comment]
Hey @vojta001! Thanks for your inputs and sorry for the delayed response. 

> Can I kindly ask what the current state of this feature is? And what are the plans? 

I think before we start to work on this feature or accept a PR for adding it, we need to agree first on the API and its implementation.

If you have a suggestion for such API, please write it here and we'll go over it. Once it's accepted, we can work on the implementation (or accept a PR for it).

**Comment by vojta001** [comment]
I don't think it implies major API changes, it is mostly about query generator. I'll try to sum it up

* There has to be a way to mark the primary key. Either by marking all the columns (which requires the ability to specify which columns is for which edge) or by marking some columns and some edges.
* All queries for relations must make sure all of the columns of the PK of the target table match.
* All relation tables have to include all the PK columns

I'll try to illustrate it:

# Example

## DB model
* Composer
  * id (PK)
  * name
  * age

* Song
  * id (part of PK)
  * composer_id (part of PK)
  * name
  * composed_on

* Playlist
  * id
  * name

* Review
  * id (part of PK)
  * song_id (part of PK, because there is a relation to song)
  * composer_id (part of PK, because song's PK contains it)
  * content

* Song:Composer is M:O relation.
* Song:Playlist is M:M relation.
* Review:Song is M:O relation.

## The Get, GeX, Only, OnlyX methods
* To obtain exactly one composer, you have to supply his id.
* To obtain exactly one song, you have to supply both its id and composer_id.
* To obtain exactly one playlist, you have to supply its id.
* To obtain exactly one review, you have to supply its id, the song_id and the composer_id.

## The internal joining mechanisms
* To query song's composer, you find it based on composer_id
* To query the review's song, you find it based on both song_id and composer_id.
* To query the review's composer (the composer of the song reviewed), you find it based on song_id and composer_id (possibly without the need to consult the song table, but this is IMO not needed to garbage the API).

## The relation tables
* The Song:Playlist relation table has to store playlist's id and song's id and song's composer_id. The are all part of PK.

**Comment by vojta001** [comment]
Does it make sense to you @a8m like this?

**Comment by vojta001** [comment]
Are there any plans on implementing this or is it blocked by something?

**Comment by vojta001** [comment]
Please @a8m, are you interested in implementing this feature?

**Comment by aight8** [comment]
Some inputs for realization:
- Remove normal ID field
- Define defined fields which are registered as pk ```PRIMARY KEY(quarter_id, course_id, student_id)```
- Alternative ID methods are generated which query WHERE all fields equals the given parameter

Solve problems:
- No ID field required per table - but there is always a unique row identification (this allows to work with all kind of table which have no such field)
- All the benefits for the developer i described above

**Comment by a8m** [comment]
Hey all and sorry for the delayed comment. 

It wasn't easy to add support for this 1 year ago, because this is an SQL-specific feature and we plan to support more database types in the future. However, we added the `ent.Annotation` option a few months ago that allows passing custom metadata for ent-codegen, and the [`entsql.Annotation`](https://pkg.go.dev/entgo.io/ent@v0.7.0/dialect/entsql#Annotation) struct for passing SQL-specific options for ent-codegen. 

I think this feature can be added by configuring the primary-key columns using `entsql.Annotation` as follows:
```go
func (UserGroup) Annotations() []schema.Annotation {
    return []schema.Annotation{
        entsql.PrimaryKey("user_id", "group_id")
    }
}

func (UserGroup) Fields() []ent.Field {
    return []ent.Field{
        field.Int("user_id"),
        field.Int("group_id"),
    }
}
```

The codegen will generate the schema-migration based on the configuration and won't generate an ID field or any setters and predicates for such PKs, but all other code parts will work the same as before.

In the future, we can consider adding an API like suggested by @aight8, but I prefer to start with a smaller change and improve/expand it in the future. 

Please share your thoughts and feedback. Thanks 🙏

**Comment by bodokaiser** [comment]
I cannot find any `entsql.PrimaryKey`?

**Comment by vojta001** [comment]
@a8m How does eager loading fit into your proposal? Will ent generate proper joins for me?

**Comment by shenghui0779** [comment]
where is `entsql.PrimaryKey` ?

**Comment by me0den** [comment]
@a8m Is the Annotation `entsql.PrimaryKey` ready to use?

**Comment by rotemtam** [comment]
@ricky26 I think you can use [edge fields](https://entgo.io/docs/schema-edges/#edge-field) for that and filter on the edge field value in cases like that. WDYT?

**Comment by ricky26** [comment]
@rotemtam IIUC you can only do that for the primary key for the edge.

So, for example, say you have a Namespace, a User and some Videos. Videos are always owned by Users and Users by namespaces, so they could have a O2M edge each.

Now, if you wanted to do a search for a Video by its title, but only a given tenant's Namespace, you can do something like:
```go
tx.Video.Query().
  Where(
      video.HasUserWith(
        user.HasNamespaceWith(
          namespace.IDEQ("my-tenant-id"),
        ),
      ),
  ).
  All(ctx)
```

However, this will result in two SQL `JOIN`s IIUC. Not the end of the world but there are some caveats.

If we could have composite keys and define edge fields for them, we could query by the embedded Namespace ID directly without a `JOIN`.

Happy to be wrong here! :smile:

**Comment by adayNU** [comment]
I think @a8m's suggestion would be sufficient for most use cases, but would also require an additional method for the `assocBuilder`, namely `Fields(fields ...string)`, who's arguments presumably would need to match the field order in the `Annotation`? that feels mildly gross... but would work.

**Comment by alv00** [comment]
hi~

1、Can I create multiple primary keys for a table now? For example, I want the schema of this table to be like this：

`CREATE TABLE `__all_sys_parameter` (
  `zone` varchar(128) NOT NULL,
  `svr_type` varchar(16) NOT NULL,
  `svr_ip` varchar(46) NOT NULL,
  .......
  PRIMARY KEY (param_name`, `zone`, `svr_type`, `svr_ip`, `svr_port`, `name`)`

2、Because I don't want to have an auto-incrementing id column, so I define the id column like this
`		field.String("id").StorageKey("param_name").SchemaType(map[string]string{
			dialect.MySQL: "varchar(128)", // Override MySQL.
		}),`
Now this table has only one primary key
`PRIMARY KEY (`param_name`)`

**Comment by alv00** [comment]
hi~

1、Can I create multiple primary keys for a table now? 
For example, I want the schema of this table to be like this：
```
CREATE TABLE `__all_sys_parameter` (
    `zone` varchar(128) NOT NULL,
    `svr_type` varchar(16) NOT NULL,
    `svr_ip` varchar(46) NOT NULL,
    .......
    PRIMARY KEY (param_name`, `zone`, `svr_type`, `svr_ip`, `svr_port`, `name`)
```

2、Because I don't want to have an auto-incrementing id column, so I define the id column like this
```
field.String("id").StorageKey("param_name").SchemaType(map[string]string{
    dialect.MySQL: "varchar(128)", // Override MySQL.
    }),
```
Now this table has only one primary key
```
PRIMARY KEY (`param_name`)
```

**Comment by oryanmoshe** [comment]
> Hey all and sorry for the delayed comment. 
> 
> 
> 
> It wasn't easy to add support for this 1 year ago, because this is an SQL-specific feature and we plan to support more database types in the future. However, we added the `ent.Annotation` option a few months ago that allows passing custom metadata for ent-codegen, and the [`entsql.Annotation`](https://pkg.go.dev/entgo.io/ent@v0.7.0/dialect/entsql#Annotation) struct for passing SQL-specific options for ent-codegen. 
> 
> 
> 
> I think this feature can be added by configuring the primary-key columns using `entsql.Annotation` as follows:
> 
> ```go
> 
> func (UserGroup) Annotations() []schema.Annotation {
> 
>     return []schema.Annotation{
> 
>         entsql.PrimaryKey("user_id", "group_id")
> 
>     }
> 
> }
> 
> 
> 
> func (UserGroup) Fields() []ent.Field {
> 
>     return []ent.Field{
> 
>         field.Int("user_id"),
> 
>         field.Int("group_id"),
> 
>     }
> 
> }
> 
> ```
> 
> 
> 
> The codegen will generate the schema-migration based on the configuration and won't generate an ID field or any setters and predicates for such PKs, but all other code parts will work the same as before.
> 
> 
> 
> In the future, we can consider adding an API like suggested by @aight8, but I prefer to start with a smaller change and improve/expand it in the future. 
> 
> 
> 
> Please share your thoughts and feedback. Thanks 🙏 


3 years later - are there any plans to add the ’PrimaryKey’ annotation to ent?
There's currently no available solution for using this basic SQL feature.

**Comment by a8m** [comment]
The composite primary key was added to edge-schemas and you can checkout the doc for it here: https://entgo.io/docs/schema-edges#user-likes-example. That's the example you mentioned above, but with slightly different syntax. 

Ent nodes/types must have an ID field (in the current API) as the many layers and integrations expect this - our GraphQL mainly. Note, `ent.View`s can be defined without an ID field.

However, that does not mean you need to set the primary key on the ID field. You can attach the `entsql.Skip` annotation to your schema, configure the `PRIMARY KEY` based on your needs, but you'll need to handle its migrations separately (you can utilize Atlas for this). 

Closing, as I don't see a reason for keeping it open. Please, use the Discord server if you need any help with the setup - I'll be happy to help.
