### ISSUE TITLE
sorry, too many clients already

### ISSUE THREAD

**Issue by mahdimahdavi-ce** [ent/ent#4245]
Hello everyone!

We have decided to use the latest version of ent for the first time in our services. it is pretty good in many things but we got a weird bug.

in our code we use this to create the ent instance for interacting with database:

	dsn := fmt.Sprintf("host=%s port=%s user=%s dbname=%s password=%s sslmode=disable", host, port, username, databaseName, password)

	client, err := ent.Open("postgres", dsn)
	if err != nil {
		log.Fatalf("Failed opening connection to postgres: %v", err)
	}

	if migrationErr := client.Schema.Create(context.Background()); migrationErr != nil {
		log.Fatalf("Failed creating schema resources: %v", migrationErr)
	}

	databaseWrapper := &DatabaseWrapper{
		Client: client,
		Logger: logger,
	}

we use this wrapper every where in the code.

couple of days ago we decided to run a k6 script for load test. It was working completely fine before this. while testing we got an error which says: 

 sorry, too many clients already
 
![Screenshot from 2024-10-21 16-21-37](https://github.com/user-attachments/assets/d829bb43-a8e4-4c3c-8b59-0201f8072248)

Based on comment, ent.Open() is supposed to create a client and return it, but it seems that is not a real client and something else is happening under the hood, because we get too many clients error

Thank you!

**Comment by a8m** [comment]
`sql.Open` creates a `sql.DB`, which holds a pool of connections to the database. The error you're encountering is returned by PostgreSQL because there are too many idle or busy connections open to the database (you can read more about it [here](https://www.postgresql.org/docs/current/runtime-config-connection.html#RUNTIME-CONFIG-CONNECTION-SETTINGS)). You can manage the connection pooling settings in the `database/sql` package, like max idle/open connections, etc.

Closing as this issue is not something in Ent, but feel free to join our Discord and ask for help if you need.
