### ISSUE TITLE
proposal: allow specifying extra constraints on UpdateOne and DeleteOne instances via Where()

### ISSUE THREAD

**Issue by DeedleFake** [ent/ent#849]
The `Where()` method is only available for `Update` and `Delete`, not for `UpdateOne` and `DeleteOne`, but it would be quite useful to be able to use it on those simply as a way of specifying extra constraints. For example, let's say that you have two entities, `A` and `B`, where `A` has an edge to `B` but that edge is unique the other direction. The user wants to update a `B` belonging to a certain `A`. Currently, the only way to ensure that the user's input is correct for both IDs is to use an `Update`, such as

```go
n, err := entc.B.Update().
  Where(b.ID(bid)).
  Where(b.HasAWith(a.ID(aid))).
  SetSomeField(something).
  Save(ctx)
```

and then manually check if `n` is in fact one. It would be convenient to be able to do

```go
b, err := entc.B.UpdateOneID(bid).
  Where(b.HasAWith(a.ID(aid))).
  SetSomeField(something).
  Save(ctx)
```

instead and let it properly fail with a `ent.IsNotFound(err) == true` error if nothing with that condition exists. Not to mention that this will return the updated entity, too.

**Comment by DeedleFake** [comment]
Here's a possible alternative: Add an equivalent of `Only()` to `Update`.

**Comment by a8m** [comment]
Hey @DeedleFake, it's possible to add extra `Where` clauses to the `UpdateOne` builder using the `Mutation` interface. It's mainly used for adding `Where` clauses in hooks, but the following code is valid:

```go
u := client.User.UpdateOneID(usr.ID)
u.Mutation().Where(user.Name("baz"))
u.Exec(ctx)
```
See additional examples in https://github.com/ent/ent/pull/1889

I'm going to close this issue atm, because it's been open for 10 months, I didn't get additional feedback on it, and the above code ~addresses it. However, I agree that adding the `Where` setter to the builder will make the API friendlier, but I still didn't encounter a case that it was needed besides hooks (+ Mutations). If you really need the `Where` API for the `UpdateOne` builders, generate it with custom templates for now.

Closing, but please let me know what do you think, or feel free to ping me on our [Slack channel](https://entgo.io/docs/slack/). I promise to update (or resolve this issue) if I'll see more usage for this feature.
